# Copyright (c) 2020 PaddlePaddle Authors. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# global settings

runner:
  train_data_dir: "./data/sample_data/train"
  train_reader_path: "aitm_reader" # importlib format
  use_gpu: False
  train_batch_size: 10
  epochs: 2
  print_interval: 10
  #model_init_path: "output_model/0" # init model
  model_save_path: "output_model_aitm_test/"
  test_data_dir: "./data/sample_data/test"
  infer_reader_path: "aitm_reader" # importlib format
  infer_batch_size: 10
  infer_load_path: "output_model_aitm_test/"
  infer_start_epoch: 0
  infer_end_epoch: 2

# hyper parameters of user-defined network
hyper_parameters:
  # optimizer config
  optimizer:
    class: Adam
    learning_rate: 0.0001
  # user-defined <key, value> pairs
  embedding_size: 5
  dims: [128, 64, 32]
  drop_prob: [0.1, 0.3, 0.3]
  feature_vocabulary: [['101', 238635], ['121', 98], ['122', 14], ['124', 3], ['125', 8], ['126', 4], ['127', 4], ['128', 3], ['129', 5], ['205', 467298], ['206', 6929], ['207', 263942], ['216', 106399], ['508', 5888], ['509', 104830], ['702', 51878], ['853', 37148], ['301', 4]]
