# Copyright (c) 2020 PaddlePaddle Authors. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

#workspace: "paddlerec.models.demo.movie_recommand"
workspace: "./"
# list of dataset
dataset:
- name: dataset_infer # name
  batch_size: 128
  type: DataLoader
  data_path: "{workspace}/data/test"
  sparse_slots: "logid time userid gender age occupation movieid title genres label"
  dense_slots: ""

# hyper parameters of user-defined network
hyper_parameters:
  # optimizer config
  optimizer:
    class: Adam
    learning_rate: 0.001
    strategy: async
  # user-defined <key, value> pairs
  sparse_feature_number: 60000000
  sparse_feature_dim: 9
  dense_input_dim: 13
  fc_sizes: [512, 256, 128, 32]

# train
mode: runner_infer

runner:
- name: runner_infer
  epochs: 1
  device: cpu
  class: infer
  print_interval: 100000
  runner_result_dump_path: "{workspace}/recall/infer_result"
  init_model_path: "increment_recall/9" # load model path


#offline infer
phase:
- name: phase1
  model: "{workspace}/recall/model.py" # user-defined model
  dataset_name: dataset_infer 
  thread_num: 1
