# Copyright (c) 2020 PaddlePaddle Authors. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
hyper_parameters:
  optimizer:
    learning_rate: 1.0
    decay_steps: 100000
    decay_rate: 0.999
  sparse_feature_number: 354051
  sparse_feature_dim: 300
  with_shuffle_batch: False
  neg_num: 5
  window_size: 5

runner:
  epochs: 20
  print_interval: 10

  sync_mode: "geo"  # sync / async /geo / heter
  geo_step: 400
  thread_num: 16
  use_gpu: 0
  
  model_path: "static_model.py"
  train_reader_path: "static_reader.py"
  reader_type: "QueueDataset"  # DataLoader / QueueDataset
  dataset_debug: False
  pipe_command: "python static_reader.py"
  example_count_method: "word"
  dataset_debug: False
  split_file_list: False

  train_batch_size: 100
  train_data_dir: "train_data"
  train_reader_path: "static_ps_reader.py"
  model_save_path: "model"

  word_count_dict_path: "{workspace}/dict/word_count_dict.txt"
  word_id_dict_path: "{workspace}/dict/word_id_dict.txt"
