# Copyright (c) 2020 PaddlePaddle Authors. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

runner:
  train_data_dir: "data/sample_data"
  train_reader_path: "movielens_reader"  # importlib format
  train_batch_size: 512
  model_save_path: "output_model_ensfm"
  mode: "test"
  use_gpu: False
  epochs: 3
  print_interval: 10
  
  test_data_dir: "data/sample_data"
  infer_reader_path: "movielens_reader"  # importlib format
  infer_batch_size: 1
  infer_load_path: "output_model_ensfm"
  infer_start_epoch: 2
  infer_end_epoch: 3

hyper_parameters:
  optimizer: 
    class: adam
    learning_rate: 0.05
  num_users: 6069
  num_items: 3953
  mf_dim: 8
  mode: "train"
  negative_weight: 0.5
