# Copyright (c) 2020 PaddlePaddle Authors. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
runner:
  train_data_dir: "pgl_BlogCatalogDataset"
  train_reader_path: ""
  train_batch_size: 5156
  model_save_path: "output_model_multi_class"

  use_gpu: True
  epochs: 1
  print_interval: 1
  
  test_data_dir: "pgl_BlogCatalogDataset"
  infer_reader_path: ""
  infer_batch_size: 5156
  infer_load_path: "output_model_multi_class"
  infer_start_epoch: 0
  infer_end_epoch: 1

  reader_type: "CustomizeDataLoader"
  # model_init_path: "../output_mode_deepwalk/0"
  use_save_data: True

hyper_parameters:
  optimizer: 
    class: adam
    learning_rate: 0.025
  sample_workers: 10
  neg_num: 20
  walk_len: 40
  win_size: 10
  neg_sample_type: average
  embed_size: 128
  num_emb_part: 8
