# Copyright (c) 2020 PaddlePaddle Authors. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


workspace: "models/recall/youtube_dnn"

dataset:
- name: dataset_train
  batch_size: 32
  type: DataLoader # or QueueDataset
  data_path: "{workspace}/data/train"
  data_converter: "{workspace}/reader.py"

hyper_parameters:
  watch_vec_size: 64
  search_vec_size: 64
  other_feat_size: 64
  output_size: 100
  layers: [128, 64, 32]
  optimizer: 
    class: SGD
    learning_rate: 0.01

mode: [cpu_single_train]

runner:
- name: cpu_single_train
  class: train
  device: cpu
  epochs: 20
  save_checkpoint_interval: 1
  save_inference_interval: 1
  save_checkpoint_path: "increment_youtubednn"
  save_inference_path: "inference_youtubednn"
  save_inference_feed_varnames: ["watch_vec", "search_vec", "other_feat"] # feed vars of save inference
  save_inference_fetch_varnames: ["l3.tmp_2"]
  print_interval: 1

phase:
- name: train
  model: "{workspace}/model.py"
  dataset_name: dataset_train
  thread_num: 1
