# Copyright (c) 2020 PaddlePaddle Authors. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# workspace
#workspace: "models/rank/dnn"


runner:
  train_data_dir: "data/"
  train_reader_path: "criteo_reader" # importlib format
  use_gpu: False
  use_auc: True
  train_batch_size: 2
  epochs: 3
  print_interval: 10
  model_save_path: "output_model_benchdnn_queue"

  thread_num: 1
  reader_type: "QueueDataset"  # DataLoader / QueueDataset / RecDataset
  pipe_command: "python3.7 queuedataset_reader.py"
  dataset_debug: False
  split_file_list: False

  infer_batch_size: 2
  infer_reader_path: "criteo_reader" # importlib format
  test_data_dir: "data/"
  infer_load_path: "output_model_benchdnn_queue"
  infer_start_epoch: 0
  infer_end_epoch: 3
  use_inference: True
  save_inference_feed_varnames: ["concat_0.tmp_0"]
  save_inference_fetch_varnames: ["sigmoid_0.tmp_0"]
# hyper parameters of user-defined network
hyper_parameters:
  # optimizer config
  optimizer:
    class: Adam
    learning_rate: 0.001
    strategy: async
  # user-defined <key, value> pairs
  dict_dim : 1000000
  emb_dim : 9
  sparse_feature_dim: 9
  slot_num: 408
  layer_sizes: [512, 256, 128, 128, 128]
  distributed_embedding: 0
