blocks {
  idx: 0
  parent_idx: -1
  vars {
    name: "fc_7.tmp_0"
    type {
      type: LOD_TENSOR
      lod_tensor {
        tensor {
          data_type: FP32
          dims: -1
          dims: 1
        }
        lod_level: 0
      }
    }
    persistable: false
  }
  vars {
    name: "fc_7.tmp_1"
    type {
      type: LOD_TENSOR
      lod_tensor {
        tensor {
          data_type: FP32
          dims: -1
          dims: 1
        }
        lod_level: 0
      }
    }
    persistable: false
  }
  vars {
    name: "bn6048.batch_square_sum"
    type {
      type: LOD_TENSOR
      lod_tensor {
        tensor {
          data_type: FP32
          dims: 4488
        }
      }
    }
    persistable: true
  }
  vars {
    name: "fc_0.tmp_1"
    type {
      type: LOD_TENSOR
      lod_tensor {
        tensor {
          data_type: FP32
          dims: -1
          dims: 511
        }
        lod_level: 0
      }
    }
    persistable: false
  }
  vars {
    name: "fc_7.w_0"
    type {
      type: LOD_TENSOR
      lod_tensor {
        tensor {
          data_type: FP32
          dims: 127
          dims: 1
        }
      }
    }
    persistable: true
  }
  vars {
    name: "fc_1.tmp_2"
    type {
      type: LOD_TENSOR
      lod_tensor {
        tensor {
          data_type: FP32
          dims: -1
          dims: 255
        }
        lod_level: 0
      }
    }
    persistable: false
  }
  vars {
    name: "fc_7.b_0"
    type {
      type: LOD_TENSOR
      lod_tensor {
        tensor {
          data_type: FP32
          dims: 1
        }
      }
    }
    persistable: true
  }
  vars {
    name: "fc_6.tmp_2"
    type {
      type: LOD_TENSOR
      lod_tensor {
        tensor {
          data_type: FP32
          dims: -1
          dims: 127
        }
        lod_level: 0
      }
    }
    persistable: false
  }
  vars {
    name: "fc_0.tmp_2"
    type {
      type: LOD_TENSOR
      lod_tensor {
        tensor {
          data_type: FP32
          dims: -1
          dims: 511
        }
        lod_level: 0
      }
    }
    persistable: false
  }
  vars {
    name: "_generated_var_0"
    type {
      type: LOD_TENSOR
      lod_tensor {
        tensor {
          data_type: FP32
          dims: 4488
        }
      }
    }
  }
  vars {
    name: "fc_4.w_0"
    type {
      type: LOD_TENSOR
      lod_tensor {
        tensor {
          data_type: FP32
          dims: 127
          dims: 127
        }
      }
    }
    persistable: true
  }
  vars {
    name: "clip_0.tmp_0"
    type {
      type: LOD_TENSOR
      lod_tensor {
        tensor {
          data_type: FP32
          dims: -1
          dims: 1
        }
        lod_level: 0
      }
    }
    persistable: false
  }
  vars {
    name: "fc_3.w_0"
    type {
      type: LOD_TENSOR
      lod_tensor {
        tensor {
          data_type: FP32
          dims: 255
          dims: 127
        }
      }
    }
    persistable: true
  }
  vars {
    name: "fc_2.tmp_2"
    type {
      type: LOD_TENSOR
      lod_tensor {
        tensor {
          data_type: FP32
          dims: -1
          dims: 255
        }
        lod_level: 0
      }
    }
    persistable: false
  }
  vars {
    name: "cvm_input"
    type {
      type: LOD_TENSOR
      lod_tensor {
        tensor {
          data_type: FP32
          dims: -1
          dims: 4488
        }
        lod_level: 0
      }
    }
    persistable: false
  }
  vars {
    name: "fc_0.tmp_0"
    type {
      type: LOD_TENSOR
      lod_tensor {
        tensor {
          data_type: FP32
          dims: -1
          dims: 511
        }
        lod_level: 0
      }
    }
    persistable: false
  }
  vars {
    name: "bn6048.batch_sum"
    type {
      type: LOD_TENSOR
      lod_tensor {
        tensor {
          data_type: FP32
          dims: 4488
        }
      }
    }
    persistable: true
  }
  vars {
    name: "fc_2.tmp_1"
    type {
      type: LOD_TENSOR
      lod_tensor {
        tensor {
          data_type: FP32
          dims: -1
          dims: 255
        }
        lod_level: 0
      }
    }
    persistable: false
  }
  vars {
    name: "fc_5.tmp_0"
    type {
      type: LOD_TENSOR
      lod_tensor {
        tensor {
          data_type: FP32
          dims: -1
          dims: 127
        }
        lod_level: 0
      }
    }
    persistable: false
  }
  vars {
    name: "fc_0.b_0"
    type {
      type: LOD_TENSOR
      lod_tensor {
        tensor {
          data_type: FP32
          dims: 511
        }
      }
    }
    persistable: true
  }
  vars {
    name: "fc_1.b_0"
    type {
      type: LOD_TENSOR
      lod_tensor {
        tensor {
          data_type: FP32
          dims: 255
        }
      }
    }
    persistable: true
  }
  vars {
    name: "fc_5.b_0"
    type {
      type: LOD_TENSOR
      lod_tensor {
        tensor {
          data_type: FP32
          dims: 127
        }
      }
    }
    persistable: true
  }
  vars {
    name: "bn6048.batch_size"
    type {
      type: LOD_TENSOR
      lod_tensor {
        tensor {
          data_type: FP32
          dims: 4488
        }
      }
    }
    persistable: true
  }
  vars {
    name: "fc_2.w_0"
    type {
      type: LOD_TENSOR
      lod_tensor {
        tensor {
          data_type: FP32
          dims: 255
          dims: 255
        }
      }
    }
    persistable: true
  }
  vars {
    name: "ctr.tmp_0"
    type {
      type: LOD_TENSOR
      lod_tensor {
        tensor {
          data_type: FP32
          dims: -1
          dims: 1
        }
        lod_level: 0
      }
    }
    persistable: false
  }
  vars {
    name: "fc_1.tmp_0"
    type {
      type: LOD_TENSOR
      lod_tensor {
        tensor {
          data_type: FP32
          dims: -1
          dims: 255
        }
        lod_level: 0
      }
    }
    persistable: false
  }
  vars {
    name: "fc_2.b_0"
    type {
      type: LOD_TENSOR
      lod_tensor {
        tensor {
          data_type: FP32
          dims: 255
        }
      }
    }
    persistable: true
  }
  vars {
    name: "fc_4.tmp_2"
    type {
      type: LOD_TENSOR
      lod_tensor {
        tensor {
          data_type: FP32
          dims: -1
          dims: 127
        }
        lod_level: 0
      }
    }
    persistable: false
  }
  vars {
    name: "_generated_var_1"
    type {
      type: LOD_TENSOR
      lod_tensor {
        tensor {
          data_type: FP32
          dims: 4488
        }
      }
    }
  }
  vars {
    name: "_generated_var_2"
    type {
      type: LOD_TENSOR
      lod_tensor {
        tensor {
          data_type: FP32
          dims: -1
          dims: 4488
        }
        lod_level: 0
      }
    }
  }
  vars {
    name: "fc_3.tmp_0"
    type {
      type: LOD_TENSOR
      lod_tensor {
        tensor {
          data_type: FP32
          dims: -1
          dims: 127
        }
        lod_level: 0
      }
    }
    persistable: false
  }
  vars {
    name: "fc_3.b_0"
    type {
      type: LOD_TENSOR
      lod_tensor {
        tensor {
          data_type: FP32
          dims: 127
        }
      }
    }
    persistable: true
  }
  vars {
    name: "fc_6.tmp_0"
    type {
      type: LOD_TENSOR
      lod_tensor {
        tensor {
          data_type: FP32
          dims: -1
          dims: 127
        }
        lod_level: 0
      }
    }
    persistable: false
  }
  vars {
    name: "fc_3.tmp_2"
    type {
      type: LOD_TENSOR
      lod_tensor {
        tensor {
          data_type: FP32
          dims: -1
          dims: 127
        }
        lod_level: 0
      }
    }
    persistable: false
  }
  vars {
    name: "fc_4.tmp_1"
    type {
      type: LOD_TENSOR
      lod_tensor {
        tensor {
          data_type: FP32
          dims: -1
          dims: 127
        }
        lod_level: 0
      }
    }
    persistable: false
  }
  vars {
    name: "fc_3.tmp_1"
    type {
      type: LOD_TENSOR
      lod_tensor {
        tensor {
          data_type: FP32
          dims: -1
          dims: 127
        }
        lod_level: 0
      }
    }
    persistable: false
  }
  vars {
    name: "fc_6.b_0"
    type {
      type: LOD_TENSOR
      lod_tensor {
        tensor {
          data_type: FP32
          dims: 127
        }
      }
    }
    persistable: true
  }
  vars {
    name: "fc_1.w_0"
    type {
      type: LOD_TENSOR
      lod_tensor {
        tensor {
          data_type: FP32
          dims: 511
          dims: 255
        }
      }
    }
    persistable: true
  }
  vars {
    name: "fc_1.tmp_1"
    type {
      type: LOD_TENSOR
      lod_tensor {
        tensor {
          data_type: FP32
          dims: -1
          dims: 255
        }
        lod_level: 0
      }
    }
    persistable: false
  }
  vars {
    name: "fc_5.w_0"
    type {
      type: LOD_TENSOR
      lod_tensor {
        tensor {
          data_type: FP32
          dims: 127
          dims: 127
        }
      }
    }
    persistable: true
  }
  vars {
    name: "fc_5.tmp_1"
    type {
      type: LOD_TENSOR
      lod_tensor {
        tensor {
          data_type: FP32
          dims: -1
          dims: 127
        }
        lod_level: 0
      }
    }
    persistable: false
  }
  vars {
    name: "fc_2.tmp_0"
    type {
      type: LOD_TENSOR
      lod_tensor {
        tensor {
          data_type: FP32
          dims: -1
          dims: 255
        }
        lod_level: 0
      }
    }
    persistable: false
  }
  vars {
    name: "fc_4.tmp_0"
    type {
      type: LOD_TENSOR
      lod_tensor {
        tensor {
          data_type: FP32
          dims: -1
          dims: 127
        }
        lod_level: 0
      }
    }
    persistable: false
  }
  vars {
    name: "fc_5.tmp_2"
    type {
      type: LOD_TENSOR
      lod_tensor {
        tensor {
          data_type: FP32
          dims: -1
          dims: 127
        }
        lod_level: 0
      }
    }
    persistable: false
  }
  vars {
    name: "fc_6.w_0"
    type {
      type: LOD_TENSOR
      lod_tensor {
        tensor {
          data_type: FP32
          dims: 127
          dims: 127
        }
      }
    }
    persistable: true
  }
  vars {
    name: "fc_6.tmp_1"
    type {
      type: LOD_TENSOR
      lod_tensor {
        tensor {
          data_type: FP32
          dims: -1
          dims: 127
        }
        lod_level: 0
      }
    }
    persistable: false
  }
  vars {
    name: "fc_0.w_0"
    type {
      type: LOD_TENSOR
      lod_tensor {
        tensor {
          data_type: FP32
          dims: 4488
          dims: 511
        }
      }
    }
    persistable: true
  }
  vars {
    name: "fc_4.b_0"
    type {
      type: LOD_TENSOR
      lod_tensor {
        tensor {
          data_type: FP32
          dims: 127
        }
      }
    }
    persistable: true
  }
  ops {
    inputs {
      parameter: "BatchSize"
      arguments: "bn6048.batch_size"
    }
    inputs {
      parameter: "BatchSquareSum"
      arguments: "bn6048.batch_square_sum"
    }
    inputs {
      parameter: "BatchSum"
      arguments: "bn6048.batch_sum"
    }
    inputs {
      parameter: "X"
      arguments: "cvm_input"
    }
    outputs {
      parameter: "Means"
      arguments: "_generated_var_0"
    }
    outputs {
      parameter: "Scales"
      arguments: "_generated_var_1"
    }
    outputs {
      parameter: "Y"
      arguments: "_generated_var_2"
    }
    type: "data_norm"
    attrs {
      name: "data_layout"
      type: STRING
      s: "NCHW"
    }
    attrs {
      name: "op_role_var"
      type: STRINGS
    }
    attrs {
      name: "op_callstack"
      type: STRINGS
      strings: "  File \"/home/xiexionghang/paddle/py-paddle/python/lib/python2.7/site-packages/paddle/fluid/framework.py\", line 1780, in append_op\n    attrs=kwargs.get(\"attrs\", None))\n"
      strings: "  File \"/home/xiexionghang/paddle/py-paddle/python/lib/python2.7/site-packages/paddle/fluid/layer_helper.py\", line 43, in append_op\n    return self.main_program.current_block().append_op(*args, **kwargs)\n"
      strings: "  File \"/home/xiexionghang/paddle/py-paddle/python/lib/python2.7/site-packages/paddle/fluid/layers/nn.py\", line 3474, in data_norm\n    attrs={\"epsilon\": epsilon})\n"
      strings: "  File \"join.py\", line 31, in inference\n    param_attr={\"batch_size\":1e4, \"batch_sum_default\":0.0, \"batch_square\":1e4})\n"
      strings: "  File \"create_programs.py\", line 100, in build_and_save\n    inference_info = self._inference()\n"
      strings: "  File \"create_programs.py\", line 187, in main\n    builder.build_and_save()\n"
      strings: "  File \"create_programs.py\", line 190, in <module>\n    main(sys.argv)\n"
    }
    attrs {
      name: "op_namescope"
      type: STRING
      s: "/"
    }
    attrs {
      name: "op_role"
      type: INT
      i: 0
    }
    attrs {
      name: "epsilon"
      type: FLOAT
      f: 9.99999974738e-05
    }
  }
  ops {
    inputs {
      parameter: "X"
      arguments: "_generated_var_2"
    }
    inputs {
      parameter: "Y"
      arguments: "fc_0.w_0"
    }
    outputs {
      parameter: "Out"
      arguments: "fc_0.tmp_0"
    }
    type: "mul"
    attrs {
      name: "op_role_var"
      type: STRINGS
    }
    attrs {
      name: "x_num_col_dims"
      type: INT
      i: 1
    }
    attrs {
      name: "force_fp32_output"
      type: BOOLEAN
      b: false
    }
    attrs {
      name: "y_num_col_dims"
      type: INT
      i: 1
    }
    attrs {
      name: "op_role"
      type: INT
      i: 0
    }
    attrs {
      name: "op_namescope"
      type: STRING
      s: "/"
    }
    attrs {
      name: "op_callstack"
      type: STRINGS
      strings: "  File \"/home/xiexionghang/paddle/py-paddle/python/lib/python2.7/site-packages/paddle/fluid/framework.py\", line 1780, in append_op\n    attrs=kwargs.get(\"attrs\", None))\n"
      strings: "  File \"/home/xiexionghang/paddle/py-paddle/python/lib/python2.7/site-packages/paddle/fluid/layer_helper.py\", line 43, in append_op\n    return self.main_program.current_block().append_op(*args, **kwargs)\n"
      strings: "  File \"/home/xiexionghang/paddle/py-paddle/python/lib/python2.7/site-packages/paddle/fluid/layers/nn.py\", line 345, in fc\n    \"y_num_col_dims\": 1})\n"
      strings: "  File \"join.py\", line 51, in inference\n    initializer=fluid.initializer.NormalInitializer(loc=0.0, scale=1.0 * scales[i])))\n"
      strings: "  File \"create_programs.py\", line 100, in build_and_save\n    inference_info = self._inference()\n"
      strings: "  File \"create_programs.py\", line 187, in main\n    builder.build_and_save()\n"
      strings: "  File \"create_programs.py\", line 190, in <module>\n    main(sys.argv)\n"
    }
    attrs {
      name: "use_mkldnn"
      type: BOOLEAN
      b: false
    }
    attrs {
      name: "scale_out"
      type: FLOAT
      f: 1.0
    }
    attrs {
      name: "scale_x"
      type: FLOAT
      f: 1.0
    }
    attrs {
      name: "scale_y"
      type: FLOATS
      floats: 1.0
    }
  }
  ops {
    inputs {
      parameter: "X"
      arguments: "fc_0.tmp_0"
    }
    inputs {
      parameter: "Y"
      arguments: "fc_0.b_0"
    }
    outputs {
      parameter: "Out"
      arguments: "fc_0.tmp_1"
    }
    type: "elementwise_add"
    attrs {
      name: "y_data_format"
      type: STRING
      s: ""
    }
    attrs {
      name: "x_data_format"
      type: STRING
      s: ""
    }
    attrs {
      name: "use_mkldnn"
      type: BOOLEAN
      b: false
    }
    attrs {
      name: "op_role_var"
      type: STRINGS
    }
    attrs {
      name: "op_callstack"
      type: STRINGS
      strings: "  File \"/home/xiexionghang/paddle/py-paddle/python/lib/python2.7/site-packages/paddle/fluid/framework.py\", line 1780, in append_op\n    attrs=kwargs.get(\"attrs\", None))\n"
      strings: "  File \"/home/xiexionghang/paddle/py-paddle/python/lib/python2.7/site-packages/paddle/fluid/layer_helper.py\", line 43, in append_op\n    return self.main_program.current_block().append_op(*args, **kwargs)\n"
      strings: "  File \"/home/xiexionghang/paddle/py-paddle/python/lib/python2.7/site-packages/paddle/fluid/layer_helper.py\", line 135, in append_bias_op\n    attrs={\'axis\': dim_start})\n"
      strings: "  File \"/home/xiexionghang/paddle/py-paddle/python/lib/python2.7/site-packages/paddle/fluid/layers/nn.py\", line 358, in fc\n    pre_activation = helper.append_bias_op(pre_bias, dim_start=num_flatten_dims)\n"
      strings: "  File \"join.py\", line 51, in inference\n    initializer=fluid.initializer.NormalInitializer(loc=0.0, scale=1.0 * scales[i])))\n"
      strings: "  File \"create_programs.py\", line 100, in build_and_save\n    inference_info = self._inference()\n"
      strings: "  File \"create_programs.py\", line 187, in main\n    builder.build_and_save()\n"
      strings: "  File \"create_programs.py\", line 190, in <module>\n    main(sys.argv)\n"
    }
    attrs {
      name: "op_namescope"
      type: STRING
      s: "/"
    }
    attrs {
      name: "op_role"
      type: INT
      i: 0
    }
    attrs {
      name: "axis"
      type: INT
      i: 1
    }
  }
  ops {
    inputs {
      parameter: "X"
      arguments: "fc_0.tmp_1"
    }
    outputs {
      parameter: "Out"
      arguments: "fc_0.tmp_2"
    }
    type: "relu"
    attrs {
      name: "is_test"
      type: INT
      i: 1
    }
    attrs {
      name: "use_cudnn"
      type: BOOLEAN
      b: false
    }
    attrs {
      name: "use_mkldnn"
      type: BOOLEAN
      b: false
    }
    attrs {
      name: "op_role_var"
      type: STRINGS
    }
    attrs {
      name: "op_callstack"
      type: STRINGS
      strings: "  File \"/home/xiexionghang/paddle/py-paddle/python/lib/python2.7/site-packages/paddle/fluid/framework.py\", line 1780, in append_op\n    attrs=kwargs.get(\"attrs\", None))\n"
      strings: "  File \"/home/xiexionghang/paddle/py-paddle/python/lib/python2.7/site-packages/paddle/fluid/layer_helper.py\", line 43, in append_op\n    return self.main_program.current_block().append_op(*args, **kwargs)\n"
      strings: "  File \"/home/xiexionghang/paddle/py-paddle/python/lib/python2.7/site-packages/paddle/fluid/layer_helper.py\", line 159, in append_activation\n    attrs=act)\n"
      strings: "  File \"/home/xiexionghang/paddle/py-paddle/python/lib/python2.7/site-packages/paddle/fluid/layers/nn.py\", line 360, in fc\n    return helper.append_activation(pre_activation)\n"
      strings: "  File \"join.py\", line 51, in inference\n    initializer=fluid.initializer.NormalInitializer(loc=0.0, scale=1.0 * scales[i])))\n"
      strings: "  File \"create_programs.py\", line 100, in build_and_save\n    inference_info = self._inference()\n"
      strings: "  File \"create_programs.py\", line 187, in main\n    builder.build_and_save()\n"
      strings: "  File \"create_programs.py\", line 190, in <module>\n    main(sys.argv)\n"
    }
    attrs {
      name: "op_namescope"
      type: STRING
      s: "/"
    }
    attrs {
      name: "op_role"
      type: INT
      i: 0
    }
  }
  ops {
    inputs {
      parameter: "X"
      arguments: "fc_0.tmp_2"
    }
    inputs {
      parameter: "Y"
      arguments: "fc_1.w_0"
    }
    outputs {
      parameter: "Out"
      arguments: "fc_1.tmp_0"
    }
    type: "mul"
    attrs {
      name: "op_role_var"
      type: STRINGS
    }
    attrs {
      name: "x_num_col_dims"
      type: INT
      i: 1
    }
    attrs {
      name: "force_fp32_output"
      type: BOOLEAN
      b: false
    }
    attrs {
      name: "y_num_col_dims"
      type: INT
      i: 1
    }
    attrs {
      name: "op_role"
      type: INT
      i: 0
    }
    attrs {
      name: "op_namescope"
      type: STRING
      s: "/"
    }
    attrs {
      name: "op_callstack"
      type: STRINGS
      strings: "  File \"/home/xiexionghang/paddle/py-paddle/python/lib/python2.7/site-packages/paddle/fluid/framework.py\", line 1780, in append_op\n    attrs=kwargs.get(\"attrs\", None))\n"
      strings: "  File \"/home/xiexionghang/paddle/py-paddle/python/lib/python2.7/site-packages/paddle/fluid/layer_helper.py\", line 43, in append_op\n    return self.main_program.current_block().append_op(*args, **kwargs)\n"
      strings: "  File \"/home/xiexionghang/paddle/py-paddle/python/lib/python2.7/site-packages/paddle/fluid/layers/nn.py\", line 345, in fc\n    \"y_num_col_dims\": 1})\n"
      strings: "  File \"join.py\", line 51, in inference\n    initializer=fluid.initializer.NormalInitializer(loc=0.0, scale=1.0 * scales[i])))\n"
      strings: "  File \"create_programs.py\", line 100, in build_and_save\n    inference_info = self._inference()\n"
      strings: "  File \"create_programs.py\", line 187, in main\n    builder.build_and_save()\n"
      strings: "  File \"create_programs.py\", line 190, in <module>\n    main(sys.argv)\n"
    }
    attrs {
      name: "use_mkldnn"
      type: BOOLEAN
      b: false
    }
    attrs {
      name: "scale_out"
      type: FLOAT
      f: 1.0
    }
    attrs {
      name: "scale_x"
      type: FLOAT
      f: 1.0
    }
    attrs {
      name: "scale_y"
      type: FLOATS
      floats: 1.0
    }
  }
  ops {
    inputs {
      parameter: "X"
      arguments: "fc_1.tmp_0"
    }
    inputs {
      parameter: "Y"
      arguments: "fc_1.b_0"
    }
    outputs {
      parameter: "Out"
      arguments: "fc_1.tmp_1"
    }
    type: "elementwise_add"
    attrs {
      name: "y_data_format"
      type: STRING
      s: ""
    }
    attrs {
      name: "x_data_format"
      type: STRING
      s: ""
    }
    attrs {
      name: "use_mkldnn"
      type: BOOLEAN
      b: false
    }
    attrs {
      name: "op_role_var"
      type: STRINGS
    }
    attrs {
      name: "op_callstack"
      type: STRINGS
      strings: "  File \"/home/xiexionghang/paddle/py-paddle/python/lib/python2.7/site-packages/paddle/fluid/framework.py\", line 1780, in append_op\n    attrs=kwargs.get(\"attrs\", None))\n"
      strings: "  File \"/home/xiexionghang/paddle/py-paddle/python/lib/python2.7/site-packages/paddle/fluid/layer_helper.py\", line 43, in append_op\n    return self.main_program.current_block().append_op(*args, **kwargs)\n"
      strings: "  File \"/home/xiexionghang/paddle/py-paddle/python/lib/python2.7/site-packages/paddle/fluid/layer_helper.py\", line 135, in append_bias_op\n    attrs={\'axis\': dim_start})\n"
      strings: "  File \"/home/xiexionghang/paddle/py-paddle/python/lib/python2.7/site-packages/paddle/fluid/layers/nn.py\", line 358, in fc\n    pre_activation = helper.append_bias_op(pre_bias, dim_start=num_flatten_dims)\n"
      strings: "  File \"join.py\", line 51, in inference\n    initializer=fluid.initializer.NormalInitializer(loc=0.0, scale=1.0 * scales[i])))\n"
      strings: "  File \"create_programs.py\", line 100, in build_and_save\n    inference_info = self._inference()\n"
      strings: "  File \"create_programs.py\", line 187, in main\n    builder.build_and_save()\n"
      strings: "  File \"create_programs.py\", line 190, in <module>\n    main(sys.argv)\n"
    }
    attrs {
      name: "op_namescope"
      type: STRING
      s: "/"
    }
    attrs {
      name: "op_role"
      type: INT
      i: 0
    }
    attrs {
      name: "axis"
      type: INT
      i: 1
    }
  }
  ops {
    inputs {
      parameter: "X"
      arguments: "fc_1.tmp_1"
    }
    outputs {
      parameter: "Out"
      arguments: "fc_1.tmp_2"
    }
    type: "relu"
    attrs {
      name: "is_test"
      type: INT
      i: 1
    }
    attrs {
      name: "use_cudnn"
      type: BOOLEAN
      b: false
    }
    attrs {
      name: "use_mkldnn"
      type: BOOLEAN
      b: false
    }
    attrs {
      name: "op_role_var"
      type: STRINGS
    }
    attrs {
      name: "op_callstack"
      type: STRINGS
      strings: "  File \"/home/xiexionghang/paddle/py-paddle/python/lib/python2.7/site-packages/paddle/fluid/framework.py\", line 1780, in append_op\n    attrs=kwargs.get(\"attrs\", None))\n"
      strings: "  File \"/home/xiexionghang/paddle/py-paddle/python/lib/python2.7/site-packages/paddle/fluid/layer_helper.py\", line 43, in append_op\n    return self.main_program.current_block().append_op(*args, **kwargs)\n"
      strings: "  File \"/home/xiexionghang/paddle/py-paddle/python/lib/python2.7/site-packages/paddle/fluid/layer_helper.py\", line 159, in append_activation\n    attrs=act)\n"
      strings: "  File \"/home/xiexionghang/paddle/py-paddle/python/lib/python2.7/site-packages/paddle/fluid/layers/nn.py\", line 360, in fc\n    return helper.append_activation(pre_activation)\n"
      strings: "  File \"join.py\", line 51, in inference\n    initializer=fluid.initializer.NormalInitializer(loc=0.0, scale=1.0 * scales[i])))\n"
      strings: "  File \"create_programs.py\", line 100, in build_and_save\n    inference_info = self._inference()\n"
      strings: "  File \"create_programs.py\", line 187, in main\n    builder.build_and_save()\n"
      strings: "  File \"create_programs.py\", line 190, in <module>\n    main(sys.argv)\n"
    }
    attrs {
      name: "op_namescope"
      type: STRING
      s: "/"
    }
    attrs {
      name: "op_role"
      type: INT
      i: 0
    }
  }
  ops {
    inputs {
      parameter: "X"
      arguments: "fc_1.tmp_2"
    }
    inputs {
      parameter: "Y"
      arguments: "fc_2.w_0"
    }
    outputs {
      parameter: "Out"
      arguments: "fc_2.tmp_0"
    }
    type: "mul"
    attrs {
      name: "op_role_var"
      type: STRINGS
    }
    attrs {
      name: "x_num_col_dims"
      type: INT
      i: 1
    }
    attrs {
      name: "force_fp32_output"
      type: BOOLEAN
      b: false
    }
    attrs {
      name: "y_num_col_dims"
      type: INT
      i: 1
    }
    attrs {
      name: "op_role"
      type: INT
      i: 0
    }
    attrs {
      name: "op_namescope"
      type: STRING
      s: "/"
    }
    attrs {
      name: "op_callstack"
      type: STRINGS
      strings: "  File \"/home/xiexionghang/paddle/py-paddle/python/lib/python2.7/site-packages/paddle/fluid/framework.py\", line 1780, in append_op\n    attrs=kwargs.get(\"attrs\", None))\n"
      strings: "  File \"/home/xiexionghang/paddle/py-paddle/python/lib/python2.7/site-packages/paddle/fluid/layer_helper.py\", line 43, in append_op\n    return self.main_program.current_block().append_op(*args, **kwargs)\n"
      strings: "  File \"/home/xiexionghang/paddle/py-paddle/python/lib/python2.7/site-packages/paddle/fluid/layers/nn.py\", line 345, in fc\n    \"y_num_col_dims\": 1})\n"
      strings: "  File \"join.py\", line 51, in inference\n    initializer=fluid.initializer.NormalInitializer(loc=0.0, scale=1.0 * scales[i])))\n"
      strings: "  File \"create_programs.py\", line 100, in build_and_save\n    inference_info = self._inference()\n"
      strings: "  File \"create_programs.py\", line 187, in main\n    builder.build_and_save()\n"
      strings: "  File \"create_programs.py\", line 190, in <module>\n    main(sys.argv)\n"
    }
    attrs {
      name: "use_mkldnn"
      type: BOOLEAN
      b: false
    }
    attrs {
      name: "scale_out"
      type: FLOAT
      f: 1.0
    }
    attrs {
      name: "scale_x"
      type: FLOAT
      f: 1.0
    }
    attrs {
      name: "scale_y"
      type: FLOATS
      floats: 1.0
    }
  }
  ops {
    inputs {
      parameter: "X"
      arguments: "fc_2.tmp_0"
    }
    inputs {
      parameter: "Y"
      arguments: "fc_2.b_0"
    }
    outputs {
      parameter: "Out"
      arguments: "fc_2.tmp_1"
    }
    type: "elementwise_add"
    attrs {
      name: "y_data_format"
      type: STRING
      s: ""
    }
    attrs {
      name: "x_data_format"
      type: STRING
      s: ""
    }
    attrs {
      name: "use_mkldnn"
      type: BOOLEAN
      b: false
    }
    attrs {
      name: "op_role_var"
      type: STRINGS
    }
    attrs {
      name: "op_callstack"
      type: STRINGS
      strings: "  File \"/home/xiexionghang/paddle/py-paddle/python/lib/python2.7/site-packages/paddle/fluid/framework.py\", line 1780, in append_op\n    attrs=kwargs.get(\"attrs\", None))\n"
      strings: "  File \"/home/xiexionghang/paddle/py-paddle/python/lib/python2.7/site-packages/paddle/fluid/layer_helper.py\", line 43, in append_op\n    return self.main_program.current_block().append_op(*args, **kwargs)\n"
      strings: "  File \"/home/xiexionghang/paddle/py-paddle/python/lib/python2.7/site-packages/paddle/fluid/layer_helper.py\", line 135, in append_bias_op\n    attrs={\'axis\': dim_start})\n"
      strings: "  File \"/home/xiexionghang/paddle/py-paddle/python/lib/python2.7/site-packages/paddle/fluid/layers/nn.py\", line 358, in fc\n    pre_activation = helper.append_bias_op(pre_bias, dim_start=num_flatten_dims)\n"
      strings: "  File \"join.py\", line 51, in inference\n    initializer=fluid.initializer.NormalInitializer(loc=0.0, scale=1.0 * scales[i])))\n"
      strings: "  File \"create_programs.py\", line 100, in build_and_save\n    inference_info = self._inference()\n"
      strings: "  File \"create_programs.py\", line 187, in main\n    builder.build_and_save()\n"
      strings: "  File \"create_programs.py\", line 190, in <module>\n    main(sys.argv)\n"
    }
    attrs {
      name: "op_namescope"
      type: STRING
      s: "/"
    }
    attrs {
      name: "op_role"
      type: INT
      i: 0
    }
    attrs {
      name: "axis"
      type: INT
      i: 1
    }
  }
  ops {
    inputs {
      parameter: "X"
      arguments: "fc_2.tmp_1"
    }
    outputs {
      parameter: "Out"
      arguments: "fc_2.tmp_2"
    }
    type: "relu"
    attrs {
      name: "is_test"
      type: INT
      i: 1
    }
    attrs {
      name: "use_cudnn"
      type: BOOLEAN
      b: false
    }
    attrs {
      name: "use_mkldnn"
      type: BOOLEAN
      b: false
    }
    attrs {
      name: "op_role_var"
      type: STRINGS
    }
    attrs {
      name: "op_callstack"
      type: STRINGS
      strings: "  File \"/home/xiexionghang/paddle/py-paddle/python/lib/python2.7/site-packages/paddle/fluid/framework.py\", line 1780, in append_op\n    attrs=kwargs.get(\"attrs\", None))\n"
      strings: "  File \"/home/xiexionghang/paddle/py-paddle/python/lib/python2.7/site-packages/paddle/fluid/layer_helper.py\", line 43, in append_op\n    return self.main_program.current_block().append_op(*args, **kwargs)\n"
      strings: "  File \"/home/xiexionghang/paddle/py-paddle/python/lib/python2.7/site-packages/paddle/fluid/layer_helper.py\", line 159, in append_activation\n    attrs=act)\n"
      strings: "  File \"/home/xiexionghang/paddle/py-paddle/python/lib/python2.7/site-packages/paddle/fluid/layers/nn.py\", line 360, in fc\n    return helper.append_activation(pre_activation)\n"
      strings: "  File \"join.py\", line 51, in inference\n    initializer=fluid.initializer.NormalInitializer(loc=0.0, scale=1.0 * scales[i])))\n"
      strings: "  File \"create_programs.py\", line 100, in build_and_save\n    inference_info = self._inference()\n"
      strings: "  File \"create_programs.py\", line 187, in main\n    builder.build_and_save()\n"
      strings: "  File \"create_programs.py\", line 190, in <module>\n    main(sys.argv)\n"
    }
    attrs {
      name: "op_namescope"
      type: STRING
      s: "/"
    }
    attrs {
      name: "op_role"
      type: INT
      i: 0
    }
  }
  ops {
    inputs {
      parameter: "X"
      arguments: "fc_2.tmp_2"
    }
    inputs {
      parameter: "Y"
      arguments: "fc_3.w_0"
    }
    outputs {
      parameter: "Out"
      arguments: "fc_3.tmp_0"
    }
    type: "mul"
    attrs {
      name: "op_role_var"
      type: STRINGS
    }
    attrs {
      name: "x_num_col_dims"
      type: INT
      i: 1
    }
    attrs {
      name: "force_fp32_output"
      type: BOOLEAN
      b: false
    }
    attrs {
      name: "y_num_col_dims"
      type: INT
      i: 1
    }
    attrs {
      name: "op_role"
      type: INT
      i: 0
    }
    attrs {
      name: "op_namescope"
      type: STRING
      s: "/"
    }
    attrs {
      name: "op_callstack"
      type: STRINGS
      strings: "  File \"/home/xiexionghang/paddle/py-paddle/python/lib/python2.7/site-packages/paddle/fluid/framework.py\", line 1780, in append_op\n    attrs=kwargs.get(\"attrs\", None))\n"
      strings: "  File \"/home/xiexionghang/paddle/py-paddle/python/lib/python2.7/site-packages/paddle/fluid/layer_helper.py\", line 43, in append_op\n    return self.main_program.current_block().append_op(*args, **kwargs)\n"
      strings: "  File \"/home/xiexionghang/paddle/py-paddle/python/lib/python2.7/site-packages/paddle/fluid/layers/nn.py\", line 345, in fc\n    \"y_num_col_dims\": 1})\n"
      strings: "  File \"join.py\", line 51, in inference\n    initializer=fluid.initializer.NormalInitializer(loc=0.0, scale=1.0 * scales[i])))\n"
      strings: "  File \"create_programs.py\", line 100, in build_and_save\n    inference_info = self._inference()\n"
      strings: "  File \"create_programs.py\", line 187, in main\n    builder.build_and_save()\n"
      strings: "  File \"create_programs.py\", line 190, in <module>\n    main(sys.argv)\n"
    }
    attrs {
      name: "use_mkldnn"
      type: BOOLEAN
      b: false
    }
    attrs {
      name: "scale_out"
      type: FLOAT
      f: 1.0
    }
    attrs {
      name: "scale_x"
      type: FLOAT
      f: 1.0
    }
    attrs {
      name: "scale_y"
      type: FLOATS
      floats: 1.0
    }
  }
  ops {
    inputs {
      parameter: "X"
      arguments: "fc_3.tmp_0"
    }
    inputs {
      parameter: "Y"
      arguments: "fc_3.b_0"
    }
    outputs {
      parameter: "Out"
      arguments: "fc_3.tmp_1"
    }
    type: "elementwise_add"
    attrs {
      name: "y_data_format"
      type: STRING
      s: ""
    }
    attrs {
      name: "x_data_format"
      type: STRING
      s: ""
    }
    attrs {
      name: "use_mkldnn"
      type: BOOLEAN
      b: false
    }
    attrs {
      name: "op_role_var"
      type: STRINGS
    }
    attrs {
      name: "op_callstack"
      type: STRINGS
      strings: "  File \"/home/xiexionghang/paddle/py-paddle/python/lib/python2.7/site-packages/paddle/fluid/framework.py\", line 1780, in append_op\n    attrs=kwargs.get(\"attrs\", None))\n"
      strings: "  File \"/home/xiexionghang/paddle/py-paddle/python/lib/python2.7/site-packages/paddle/fluid/layer_helper.py\", line 43, in append_op\n    return self.main_program.current_block().append_op(*args, **kwargs)\n"
      strings: "  File \"/home/xiexionghang/paddle/py-paddle/python/lib/python2.7/site-packages/paddle/fluid/layer_helper.py\", line 135, in append_bias_op\n    attrs={\'axis\': dim_start})\n"
      strings: "  File \"/home/xiexionghang/paddle/py-paddle/python/lib/python2.7/site-packages/paddle/fluid/layers/nn.py\", line 358, in fc\n    pre_activation = helper.append_bias_op(pre_bias, dim_start=num_flatten_dims)\n"
      strings: "  File \"join.py\", line 51, in inference\n    initializer=fluid.initializer.NormalInitializer(loc=0.0, scale=1.0 * scales[i])))\n"
      strings: "  File \"create_programs.py\", line 100, in build_and_save\n    inference_info = self._inference()\n"
      strings: "  File \"create_programs.py\", line 187, in main\n    builder.build_and_save()\n"
      strings: "  File \"create_programs.py\", line 190, in <module>\n    main(sys.argv)\n"
    }
    attrs {
      name: "op_namescope"
      type: STRING
      s: "/"
    }
    attrs {
      name: "op_role"
      type: INT
      i: 0
    }
    attrs {
      name: "axis"
      type: INT
      i: 1
    }
  }
  ops {
    inputs {
      parameter: "X"
      arguments: "fc_3.tmp_1"
    }
    outputs {
      parameter: "Out"
      arguments: "fc_3.tmp_2"
    }
    type: "relu"
    attrs {
      name: "is_test"
      type: INT
      i: 1
    }
    attrs {
      name: "use_cudnn"
      type: BOOLEAN
      b: false
    }
    attrs {
      name: "use_mkldnn"
      type: BOOLEAN
      b: false
    }
    attrs {
      name: "op_role_var"
      type: STRINGS
    }
    attrs {
      name: "op_callstack"
      type: STRINGS
      strings: "  File \"/home/xiexionghang/paddle/py-paddle/python/lib/python2.7/site-packages/paddle/fluid/framework.py\", line 1780, in append_op\n    attrs=kwargs.get(\"attrs\", None))\n"
      strings: "  File \"/home/xiexionghang/paddle/py-paddle/python/lib/python2.7/site-packages/paddle/fluid/layer_helper.py\", line 43, in append_op\n    return self.main_program.current_block().append_op(*args, **kwargs)\n"
      strings: "  File \"/home/xiexionghang/paddle/py-paddle/python/lib/python2.7/site-packages/paddle/fluid/layer_helper.py\", line 159, in append_activation\n    attrs=act)\n"
      strings: "  File \"/home/xiexionghang/paddle/py-paddle/python/lib/python2.7/site-packages/paddle/fluid/layers/nn.py\", line 360, in fc\n    return helper.append_activation(pre_activation)\n"
      strings: "  File \"join.py\", line 51, in inference\n    initializer=fluid.initializer.NormalInitializer(loc=0.0, scale=1.0 * scales[i])))\n"
      strings: "  File \"create_programs.py\", line 100, in build_and_save\n    inference_info = self._inference()\n"
      strings: "  File \"create_programs.py\", line 187, in main\n    builder.build_and_save()\n"
      strings: "  File \"create_programs.py\", line 190, in <module>\n    main(sys.argv)\n"
    }
    attrs {
      name: "op_namescope"
      type: STRING
      s: "/"
    }
    attrs {
      name: "op_role"
      type: INT
      i: 0
    }
  }
  ops {
    inputs {
      parameter: "X"
      arguments: "fc_3.tmp_2"
    }
    inputs {
      parameter: "Y"
      arguments: "fc_4.w_0"
    }
    outputs {
      parameter: "Out"
      arguments: "fc_4.tmp_0"
    }
    type: "mul"
    attrs {
      name: "op_role_var"
      type: STRINGS
    }
    attrs {
      name: "x_num_col_dims"
      type: INT
      i: 1
    }
    attrs {
      name: "force_fp32_output"
      type: BOOLEAN
      b: false
    }
    attrs {
      name: "y_num_col_dims"
      type: INT
      i: 1
    }
    attrs {
      name: "op_role"
      type: INT
      i: 0
    }
    attrs {
      name: "op_namescope"
      type: STRING
      s: "/"
    }
    attrs {
      name: "op_callstack"
      type: STRINGS
      strings: "  File \"/home/xiexionghang/paddle/py-paddle/python/lib/python2.7/site-packages/paddle/fluid/framework.py\", line 1780, in append_op\n    attrs=kwargs.get(\"attrs\", None))\n"
      strings: "  File \"/home/xiexionghang/paddle/py-paddle/python/lib/python2.7/site-packages/paddle/fluid/layer_helper.py\", line 43, in append_op\n    return self.main_program.current_block().append_op(*args, **kwargs)\n"
      strings: "  File \"/home/xiexionghang/paddle/py-paddle/python/lib/python2.7/site-packages/paddle/fluid/layers/nn.py\", line 345, in fc\n    \"y_num_col_dims\": 1})\n"
      strings: "  File \"join.py\", line 51, in inference\n    initializer=fluid.initializer.NormalInitializer(loc=0.0, scale=1.0 * scales[i])))\n"
      strings: "  File \"create_programs.py\", line 100, in build_and_save\n    inference_info = self._inference()\n"
      strings: "  File \"create_programs.py\", line 187, in main\n    builder.build_and_save()\n"
      strings: "  File \"create_programs.py\", line 190, in <module>\n    main(sys.argv)\n"
    }
    attrs {
      name: "use_mkldnn"
      type: BOOLEAN
      b: false
    }
    attrs {
      name: "scale_out"
      type: FLOAT
      f: 1.0
    }
    attrs {
      name: "scale_x"
      type: FLOAT
      f: 1.0
    }
    attrs {
      name: "scale_y"
      type: FLOATS
      floats: 1.0
    }
  }
  ops {
    inputs {
      parameter: "X"
      arguments: "fc_4.tmp_0"
    }
    inputs {
      parameter: "Y"
      arguments: "fc_4.b_0"
    }
    outputs {
      parameter: "Out"
      arguments: "fc_4.tmp_1"
    }
    type: "elementwise_add"
    attrs {
      name: "y_data_format"
      type: STRING
      s: ""
    }
    attrs {
      name: "x_data_format"
      type: STRING
      s: ""
    }
    attrs {
      name: "use_mkldnn"
      type: BOOLEAN
      b: false
    }
    attrs {
      name: "op_role_var"
      type: STRINGS
    }
    attrs {
      name: "op_callstack"
      type: STRINGS
      strings: "  File \"/home/xiexionghang/paddle/py-paddle/python/lib/python2.7/site-packages/paddle/fluid/framework.py\", line 1780, in append_op\n    attrs=kwargs.get(\"attrs\", None))\n"
      strings: "  File \"/home/xiexionghang/paddle/py-paddle/python/lib/python2.7/site-packages/paddle/fluid/layer_helper.py\", line 43, in append_op\n    return self.main_program.current_block().append_op(*args, **kwargs)\n"
      strings: "  File \"/home/xiexionghang/paddle/py-paddle/python/lib/python2.7/site-packages/paddle/fluid/layer_helper.py\", line 135, in append_bias_op\n    attrs={\'axis\': dim_start})\n"
      strings: "  File \"/home/xiexionghang/paddle/py-paddle/python/lib/python2.7/site-packages/paddle/fluid/layers/nn.py\", line 358, in fc\n    pre_activation = helper.append_bias_op(pre_bias, dim_start=num_flatten_dims)\n"
      strings: "  File \"join.py\", line 51, in inference\n    initializer=fluid.initializer.NormalInitializer(loc=0.0, scale=1.0 * scales[i])))\n"
      strings: "  File \"create_programs.py\", line 100, in build_and_save\n    inference_info = self._inference()\n"
      strings: "  File \"create_programs.py\", line 187, in main\n    builder.build_and_save()\n"
      strings: "  File \"create_programs.py\", line 190, in <module>\n    main(sys.argv)\n"
    }
    attrs {
      name: "op_namescope"
      type: STRING
      s: "/"
    }
    attrs {
      name: "op_role"
      type: INT
      i: 0
    }
    attrs {
      name: "axis"
      type: INT
      i: 1
    }
  }
  ops {
    inputs {
      parameter: "X"
      arguments: "fc_4.tmp_1"
    }
    outputs {
      parameter: "Out"
      arguments: "fc_4.tmp_2"
    }
    type: "relu"
    attrs {
      name: "is_test"
      type: INT
      i: 1
    }
    attrs {
      name: "use_cudnn"
      type: BOOLEAN
      b: false
    }
    attrs {
      name: "use_mkldnn"
      type: BOOLEAN
      b: false
    }
    attrs {
      name: "op_role_var"
      type: STRINGS
    }
    attrs {
      name: "op_callstack"
      type: STRINGS
      strings: "  File \"/home/xiexionghang/paddle/py-paddle/python/lib/python2.7/site-packages/paddle/fluid/framework.py\", line 1780, in append_op\n    attrs=kwargs.get(\"attrs\", None))\n"
      strings: "  File \"/home/xiexionghang/paddle/py-paddle/python/lib/python2.7/site-packages/paddle/fluid/layer_helper.py\", line 43, in append_op\n    return self.main_program.current_block().append_op(*args, **kwargs)\n"
      strings: "  File \"/home/xiexionghang/paddle/py-paddle/python/lib/python2.7/site-packages/paddle/fluid/layer_helper.py\", line 159, in append_activation\n    attrs=act)\n"
      strings: "  File \"/home/xiexionghang/paddle/py-paddle/python/lib/python2.7/site-packages/paddle/fluid/layers/nn.py\", line 360, in fc\n    return helper.append_activation(pre_activation)\n"
      strings: "  File \"join.py\", line 51, in inference\n    initializer=fluid.initializer.NormalInitializer(loc=0.0, scale=1.0 * scales[i])))\n"
      strings: "  File \"create_programs.py\", line 100, in build_and_save\n    inference_info = self._inference()\n"
      strings: "  File \"create_programs.py\", line 187, in main\n    builder.build_and_save()\n"
      strings: "  File \"create_programs.py\", line 190, in <module>\n    main(sys.argv)\n"
    }
    attrs {
      name: "op_namescope"
      type: STRING
      s: "/"
    }
    attrs {
      name: "op_role"
      type: INT
      i: 0
    }
  }
  ops {
    inputs {
      parameter: "X"
      arguments: "fc_4.tmp_2"
    }
    inputs {
      parameter: "Y"
      arguments: "fc_5.w_0"
    }
    outputs {
      parameter: "Out"
      arguments: "fc_5.tmp_0"
    }
    type: "mul"
    attrs {
      name: "op_role_var"
      type: STRINGS
    }
    attrs {
      name: "x_num_col_dims"
      type: INT
      i: 1
    }
    attrs {
      name: "force_fp32_output"
      type: BOOLEAN
      b: false
    }
    attrs {
      name: "y_num_col_dims"
      type: INT
      i: 1
    }
    attrs {
      name: "op_role"
      type: INT
      i: 0
    }
    attrs {
      name: "op_namescope"
      type: STRING
      s: "/"
    }
    attrs {
      name: "op_callstack"
      type: STRINGS
      strings: "  File \"/home/xiexionghang/paddle/py-paddle/python/lib/python2.7/site-packages/paddle/fluid/framework.py\", line 1780, in append_op\n    attrs=kwargs.get(\"attrs\", None))\n"
      strings: "  File \"/home/xiexionghang/paddle/py-paddle/python/lib/python2.7/site-packages/paddle/fluid/layer_helper.py\", line 43, in append_op\n    return self.main_program.current_block().append_op(*args, **kwargs)\n"
      strings: "  File \"/home/xiexionghang/paddle/py-paddle/python/lib/python2.7/site-packages/paddle/fluid/layers/nn.py\", line 345, in fc\n    \"y_num_col_dims\": 1})\n"
      strings: "  File \"join.py\", line 51, in inference\n    initializer=fluid.initializer.NormalInitializer(loc=0.0, scale=1.0 * scales[i])))\n"
      strings: "  File \"create_programs.py\", line 100, in build_and_save\n    inference_info = self._inference()\n"
      strings: "  File \"create_programs.py\", line 187, in main\n    builder.build_and_save()\n"
      strings: "  File \"create_programs.py\", line 190, in <module>\n    main(sys.argv)\n"
    }
    attrs {
      name: "use_mkldnn"
      type: BOOLEAN
      b: false
    }
    attrs {
      name: "scale_out"
      type: FLOAT
      f: 1.0
    }
    attrs {
      name: "scale_x"
      type: FLOAT
      f: 1.0
    }
    attrs {
      name: "scale_y"
      type: FLOATS
      floats: 1.0
    }
  }
  ops {
    inputs {
      parameter: "X"
      arguments: "fc_5.tmp_0"
    }
    inputs {
      parameter: "Y"
      arguments: "fc_5.b_0"
    }
    outputs {
      parameter: "Out"
      arguments: "fc_5.tmp_1"
    }
    type: "elementwise_add"
    attrs {
      name: "y_data_format"
      type: STRING
      s: ""
    }
    attrs {
      name: "x_data_format"
      type: STRING
      s: ""
    }
    attrs {
      name: "use_mkldnn"
      type: BOOLEAN
      b: false
    }
    attrs {
      name: "op_role_var"
      type: STRINGS
    }
    attrs {
      name: "op_callstack"
      type: STRINGS
      strings: "  File \"/home/xiexionghang/paddle/py-paddle/python/lib/python2.7/site-packages/paddle/fluid/framework.py\", line 1780, in append_op\n    attrs=kwargs.get(\"attrs\", None))\n"
      strings: "  File \"/home/xiexionghang/paddle/py-paddle/python/lib/python2.7/site-packages/paddle/fluid/layer_helper.py\", line 43, in append_op\n    return self.main_program.current_block().append_op(*args, **kwargs)\n"
      strings: "  File \"/home/xiexionghang/paddle/py-paddle/python/lib/python2.7/site-packages/paddle/fluid/layer_helper.py\", line 135, in append_bias_op\n    attrs={\'axis\': dim_start})\n"
      strings: "  File \"/home/xiexionghang/paddle/py-paddle/python/lib/python2.7/site-packages/paddle/fluid/layers/nn.py\", line 358, in fc\n    pre_activation = helper.append_bias_op(pre_bias, dim_start=num_flatten_dims)\n"
      strings: "  File \"join.py\", line 51, in inference\n    initializer=fluid.initializer.NormalInitializer(loc=0.0, scale=1.0 * scales[i])))\n"
      strings: "  File \"create_programs.py\", line 100, in build_and_save\n    inference_info = self._inference()\n"
      strings: "  File \"create_programs.py\", line 187, in main\n    builder.build_and_save()\n"
      strings: "  File \"create_programs.py\", line 190, in <module>\n    main(sys.argv)\n"
    }
    attrs {
      name: "op_namescope"
      type: STRING
      s: "/"
    }
    attrs {
      name: "op_role"
      type: INT
      i: 0
    }
    attrs {
      name: "axis"
      type: INT
      i: 1
    }
  }
  ops {
    inputs {
      parameter: "X"
      arguments: "fc_5.tmp_1"
    }
    outputs {
      parameter: "Out"
      arguments: "fc_5.tmp_2"
    }
    type: "relu"
    attrs {
      name: "is_test"
      type: INT
      i: 1
    }
    attrs {
      name: "use_cudnn"
      type: BOOLEAN
      b: false
    }
    attrs {
      name: "use_mkldnn"
      type: BOOLEAN
      b: false
    }
    attrs {
      name: "op_role_var"
      type: STRINGS
    }
    attrs {
      name: "op_callstack"
      type: STRINGS
      strings: "  File \"/home/xiexionghang/paddle/py-paddle/python/lib/python2.7/site-packages/paddle/fluid/framework.py\", line 1780, in append_op\n    attrs=kwargs.get(\"attrs\", None))\n"
      strings: "  File \"/home/xiexionghang/paddle/py-paddle/python/lib/python2.7/site-packages/paddle/fluid/layer_helper.py\", line 43, in append_op\n    return self.main_program.current_block().append_op(*args, **kwargs)\n"
      strings: "  File \"/home/xiexionghang/paddle/py-paddle/python/lib/python2.7/site-packages/paddle/fluid/layer_helper.py\", line 159, in append_activation\n    attrs=act)\n"
      strings: "  File \"/home/xiexionghang/paddle/py-paddle/python/lib/python2.7/site-packages/paddle/fluid/layers/nn.py\", line 360, in fc\n    return helper.append_activation(pre_activation)\n"
      strings: "  File \"join.py\", line 51, in inference\n    initializer=fluid.initializer.NormalInitializer(loc=0.0, scale=1.0 * scales[i])))\n"
      strings: "  File \"create_programs.py\", line 100, in build_and_save\n    inference_info = self._inference()\n"
      strings: "  File \"create_programs.py\", line 187, in main\n    builder.build_and_save()\n"
      strings: "  File \"create_programs.py\", line 190, in <module>\n    main(sys.argv)\n"
    }
    attrs {
      name: "op_namescope"
      type: STRING
      s: "/"
    }
    attrs {
      name: "op_role"
      type: INT
      i: 0
    }
  }
  ops {
    inputs {
      parameter: "X"
      arguments: "fc_5.tmp_2"
    }
    inputs {
      parameter: "Y"
      arguments: "fc_6.w_0"
    }
    outputs {
      parameter: "Out"
      arguments: "fc_6.tmp_0"
    }
    type: "mul"
    attrs {
      name: "op_role_var"
      type: STRINGS
    }
    attrs {
      name: "x_num_col_dims"
      type: INT
      i: 1
    }
    attrs {
      name: "force_fp32_output"
      type: BOOLEAN
      b: false
    }
    attrs {
      name: "y_num_col_dims"
      type: INT
      i: 1
    }
    attrs {
      name: "op_role"
      type: INT
      i: 0
    }
    attrs {
      name: "op_namescope"
      type: STRING
      s: "/"
    }
    attrs {
      name: "op_callstack"
      type: STRINGS
      strings: "  File \"/home/xiexionghang/paddle/py-paddle/python/lib/python2.7/site-packages/paddle/fluid/framework.py\", line 1780, in append_op\n    attrs=kwargs.get(\"attrs\", None))\n"
      strings: "  File \"/home/xiexionghang/paddle/py-paddle/python/lib/python2.7/site-packages/paddle/fluid/layer_helper.py\", line 43, in append_op\n    return self.main_program.current_block().append_op(*args, **kwargs)\n"
      strings: "  File \"/home/xiexionghang/paddle/py-paddle/python/lib/python2.7/site-packages/paddle/fluid/layers/nn.py\", line 345, in fc\n    \"y_num_col_dims\": 1})\n"
      strings: "  File \"join.py\", line 51, in inference\n    initializer=fluid.initializer.NormalInitializer(loc=0.0, scale=1.0 * scales[i])))\n"
      strings: "  File \"create_programs.py\", line 100, in build_and_save\n    inference_info = self._inference()\n"
      strings: "  File \"create_programs.py\", line 187, in main\n    builder.build_and_save()\n"
      strings: "  File \"create_programs.py\", line 190, in <module>\n    main(sys.argv)\n"
    }
    attrs {
      name: "use_mkldnn"
      type: BOOLEAN
      b: false
    }
    attrs {
      name: "scale_out"
      type: FLOAT
      f: 1.0
    }
    attrs {
      name: "scale_x"
      type: FLOAT
      f: 1.0
    }
    attrs {
      name: "scale_y"
      type: FLOATS
      floats: 1.0
    }
  }
  ops {
    inputs {
      parameter: "X"
      arguments: "fc_6.tmp_0"
    }
    inputs {
      parameter: "Y"
      arguments: "fc_6.b_0"
    }
    outputs {
      parameter: "Out"
      arguments: "fc_6.tmp_1"
    }
    type: "elementwise_add"
    attrs {
      name: "y_data_format"
      type: STRING
      s: ""
    }
    attrs {
      name: "x_data_format"
      type: STRING
      s: ""
    }
    attrs {
      name: "use_mkldnn"
      type: BOOLEAN
      b: false
    }
    attrs {
      name: "op_role_var"
      type: STRINGS
    }
    attrs {
      name: "op_callstack"
      type: STRINGS
      strings: "  File \"/home/xiexionghang/paddle/py-paddle/python/lib/python2.7/site-packages/paddle/fluid/framework.py\", line 1780, in append_op\n    attrs=kwargs.get(\"attrs\", None))\n"
      strings: "  File \"/home/xiexionghang/paddle/py-paddle/python/lib/python2.7/site-packages/paddle/fluid/layer_helper.py\", line 43, in append_op\n    return self.main_program.current_block().append_op(*args, **kwargs)\n"
      strings: "  File \"/home/xiexionghang/paddle/py-paddle/python/lib/python2.7/site-packages/paddle/fluid/layer_helper.py\", line 135, in append_bias_op\n    attrs={\'axis\': dim_start})\n"
      strings: "  File \"/home/xiexionghang/paddle/py-paddle/python/lib/python2.7/site-packages/paddle/fluid/layers/nn.py\", line 358, in fc\n    pre_activation = helper.append_bias_op(pre_bias, dim_start=num_flatten_dims)\n"
      strings: "  File \"join.py\", line 51, in inference\n    initializer=fluid.initializer.NormalInitializer(loc=0.0, scale=1.0 * scales[i])))\n"
      strings: "  File \"create_programs.py\", line 100, in build_and_save\n    inference_info = self._inference()\n"
      strings: "  File \"create_programs.py\", line 187, in main\n    builder.build_and_save()\n"
      strings: "  File \"create_programs.py\", line 190, in <module>\n    main(sys.argv)\n"
    }
    attrs {
      name: "op_namescope"
      type: STRING
      s: "/"
    }
    attrs {
      name: "op_role"
      type: INT
      i: 0
    }
    attrs {
      name: "axis"
      type: INT
      i: 1
    }
  }
  ops {
    inputs {
      parameter: "X"
      arguments: "fc_6.tmp_1"
    }
    outputs {
      parameter: "Out"
      arguments: "fc_6.tmp_2"
    }
    type: "relu"
    attrs {
      name: "is_test"
      type: INT
      i: 1
    }
    attrs {
      name: "use_cudnn"
      type: BOOLEAN
      b: false
    }
    attrs {
      name: "use_mkldnn"
      type: BOOLEAN
      b: false
    }
    attrs {
      name: "op_role_var"
      type: STRINGS
    }
    attrs {
      name: "op_callstack"
      type: STRINGS
      strings: "  File \"/home/xiexionghang/paddle/py-paddle/python/lib/python2.7/site-packages/paddle/fluid/framework.py\", line 1780, in append_op\n    attrs=kwargs.get(\"attrs\", None))\n"
      strings: "  File \"/home/xiexionghang/paddle/py-paddle/python/lib/python2.7/site-packages/paddle/fluid/layer_helper.py\", line 43, in append_op\n    return self.main_program.current_block().append_op(*args, **kwargs)\n"
      strings: "  File \"/home/xiexionghang/paddle/py-paddle/python/lib/python2.7/site-packages/paddle/fluid/layer_helper.py\", line 159, in append_activation\n    attrs=act)\n"
      strings: "  File \"/home/xiexionghang/paddle/py-paddle/python/lib/python2.7/site-packages/paddle/fluid/layers/nn.py\", line 360, in fc\n    return helper.append_activation(pre_activation)\n"
      strings: "  File \"join.py\", line 51, in inference\n    initializer=fluid.initializer.NormalInitializer(loc=0.0, scale=1.0 * scales[i])))\n"
      strings: "  File \"create_programs.py\", line 100, in build_and_save\n    inference_info = self._inference()\n"
      strings: "  File \"create_programs.py\", line 187, in main\n    builder.build_and_save()\n"
      strings: "  File \"create_programs.py\", line 190, in <module>\n    main(sys.argv)\n"
    }
    attrs {
      name: "op_namescope"
      type: STRING
      s: "/"
    }
    attrs {
      name: "op_role"
      type: INT
      i: 0
    }
  }
  ops {
    inputs {
      parameter: "X"
      arguments: "fc_6.tmp_2"
    }
    inputs {
      parameter: "Y"
      arguments: "fc_7.w_0"
    }
    outputs {
      parameter: "Out"
      arguments: "fc_7.tmp_0"
    }
    type: "mul"
    attrs {
      name: "op_role_var"
      type: STRINGS
    }
    attrs {
      name: "x_num_col_dims"
      type: INT
      i: 1
    }
    attrs {
      name: "force_fp32_output"
      type: BOOLEAN
      b: false
    }
    attrs {
      name: "y_num_col_dims"
      type: INT
      i: 1
    }
    attrs {
      name: "op_role"
      type: INT
      i: 0
    }
    attrs {
      name: "op_namescope"
      type: STRING
      s: "/"
    }
    attrs {
      name: "op_callstack"
      type: STRINGS
      strings: "  File \"/home/xiexionghang/paddle/py-paddle/python/lib/python2.7/site-packages/paddle/fluid/framework.py\", line 1780, in append_op\n    attrs=kwargs.get(\"attrs\", None))\n"
      strings: "  File \"/home/xiexionghang/paddle/py-paddle/python/lib/python2.7/site-packages/paddle/fluid/layer_helper.py\", line 43, in append_op\n    return self.main_program.current_block().append_op(*args, **kwargs)\n"
      strings: "  File \"/home/xiexionghang/paddle/py-paddle/python/lib/python2.7/site-packages/paddle/fluid/layers/nn.py\", line 345, in fc\n    \"y_num_col_dims\": 1})\n"
      strings: "  File \"join.py\", line 51, in inference\n    initializer=fluid.initializer.NormalInitializer(loc=0.0, scale=1.0 * scales[i])))\n"
      strings: "  File \"create_programs.py\", line 100, in build_and_save\n    inference_info = self._inference()\n"
      strings: "  File \"create_programs.py\", line 187, in main\n    builder.build_and_save()\n"
      strings: "  File \"create_programs.py\", line 190, in <module>\n    main(sys.argv)\n"
    }
    attrs {
      name: "use_mkldnn"
      type: BOOLEAN
      b: false
    }
    attrs {
      name: "scale_out"
      type: FLOAT
      f: 1.0
    }
    attrs {
      name: "scale_x"
      type: FLOAT
      f: 1.0
    }
    attrs {
      name: "scale_y"
      type: FLOATS
      floats: 1.0
    }
  }
  ops {
    inputs {
      parameter: "X"
      arguments: "fc_7.tmp_0"
    }
    inputs {
      parameter: "Y"
      arguments: "fc_7.b_0"
    }
    outputs {
      parameter: "Out"
      arguments: "fc_7.tmp_1"
    }
    type: "elementwise_add"
    attrs {
      name: "y_data_format"
      type: STRING
      s: ""
    }
    attrs {
      name: "x_data_format"
      type: STRING
      s: ""
    }
    attrs {
      name: "use_mkldnn"
      type: BOOLEAN
      b: false
    }
    attrs {
      name: "op_role_var"
      type: STRINGS
    }
    attrs {
      name: "op_callstack"
      type: STRINGS
      strings: "  File \"/home/xiexionghang/paddle/py-paddle/python/lib/python2.7/site-packages/paddle/fluid/framework.py\", line 1780, in append_op\n    attrs=kwargs.get(\"attrs\", None))\n"
      strings: "  File \"/home/xiexionghang/paddle/py-paddle/python/lib/python2.7/site-packages/paddle/fluid/layer_helper.py\", line 43, in append_op\n    return self.main_program.current_block().append_op(*args, **kwargs)\n"
      strings: "  File \"/home/xiexionghang/paddle/py-paddle/python/lib/python2.7/site-packages/paddle/fluid/layer_helper.py\", line 135, in append_bias_op\n    attrs={\'axis\': dim_start})\n"
      strings: "  File \"/home/xiexionghang/paddle/py-paddle/python/lib/python2.7/site-packages/paddle/fluid/layers/nn.py\", line 358, in fc\n    pre_activation = helper.append_bias_op(pre_bias, dim_start=num_flatten_dims)\n"
      strings: "  File \"join.py\", line 51, in inference\n    initializer=fluid.initializer.NormalInitializer(loc=0.0, scale=1.0 * scales[i])))\n"
      strings: "  File \"create_programs.py\", line 100, in build_and_save\n    inference_info = self._inference()\n"
      strings: "  File \"create_programs.py\", line 187, in main\n    builder.build_and_save()\n"
      strings: "  File \"create_programs.py\", line 190, in <module>\n    main(sys.argv)\n"
    }
    attrs {
      name: "op_namescope"
      type: STRING
      s: "/"
    }
    attrs {
      name: "op_role"
      type: INT
      i: 0
    }
    attrs {
      name: "axis"
      type: INT
      i: 1
    }
  }
  ops {
    inputs {
      parameter: "X"
      arguments: "fc_7.tmp_1"
    }
    outputs {
      parameter: "Out"
      arguments: "clip_0.tmp_0"
    }
    type: "clip"
    attrs {
      name: "op_role_var"
      type: STRINGS
    }
    attrs {
      name: "op_callstack"
      type: STRINGS
      strings: "  File \"/home/xiexionghang/paddle/py-paddle/python/lib/python2.7/site-packages/paddle/fluid/framework.py\", line 1780, in append_op\n    attrs=kwargs.get(\"attrs\", None))\n"
      strings: "  File \"/home/xiexionghang/paddle/py-paddle/python/lib/python2.7/site-packages/paddle/fluid/layer_helper.py\", line 43, in append_op\n    return self.main_program.current_block().append_op(*args, **kwargs)\n"
      strings: "  File \"/home/xiexionghang/paddle/py-paddle/python/lib/python2.7/site-packages/paddle/fluid/layers/nn.py\", line 10681, in clip\n    outputs={\"Out\": out})\n"
      strings: "  File \"join.py\", line 52, in inference\n    ctr_output = fluid.layers.sigmoid(fluid.layers.clip(net, min=-15.0, max=15.0), name=\"ctr\")\n"
      strings: "  File \"create_programs.py\", line 100, in build_and_save\n    inference_info = self._inference()\n"
      strings: "  File \"create_programs.py\", line 187, in main\n    builder.build_and_save()\n"
      strings: "  File \"create_programs.py\", line 190, in <module>\n    main(sys.argv)\n"
    }
    attrs {
      name: "op_namescope"
      type: STRING
      s: "/"
    }
    attrs {
      name: "op_role"
      type: INT
      i: 0
    }
    attrs {
      name: "max"
      type: FLOAT
      f: 15.0
    }
    attrs {
      name: "min"
      type: FLOAT
      f: -15.0
    }
  }
  ops {
    inputs {
      parameter: "X"
      arguments: "clip_0.tmp_0"
    }
    outputs {
      parameter: "Out"
      arguments: "ctr.tmp_0"
    }
    type: "sigmoid"
    attrs {
      name: "is_test"
      type: INT
      i: 1
    }
    attrs {
      name: "use_cudnn"
      type: BOOLEAN
      b: false
    }
    attrs {
      name: "use_mkldnn"
      type: BOOLEAN
      b: false
    }
    attrs {
      name: "op_role_var"
      type: STRINGS
    }
    attrs {
      name: "op_callstack"
      type: STRINGS
      strings: "  File \"/home/xiexionghang/paddle/py-paddle/python/lib/python2.7/site-packages/paddle/fluid/framework.py\", line 1780, in append_op\n    attrs=kwargs.get(\"attrs\", None))\n"
      strings: "  File \"/home/xiexionghang/paddle/py-paddle/python/lib/python2.7/site-packages/paddle/fluid/layer_helper.py\", line 43, in append_op\n    return self.main_program.current_block().append_op(*args, **kwargs)\n"
      strings: "  File \"/home/xiexionghang/paddle/py-paddle/python/lib/python2.7/site-packages/paddle/fluid/layers/layer_function_generator.py\", line 247, in func\n    helper.append_op(type=op_type, inputs={\"X\": x}, outputs={\"Out\": output})\n"
      strings: "  File \"join.py\", line 52, in inference\n    ctr_output = fluid.layers.sigmoid(fluid.layers.clip(net, min=-15.0, max=15.0), name=\"ctr\")\n"
      strings: "  File \"create_programs.py\", line 100, in build_and_save\n    inference_info = self._inference()\n"
      strings: "  File \"create_programs.py\", line 187, in main\n    builder.build_and_save()\n"
      strings: "  File \"create_programs.py\", line 190, in <module>\n    main(sys.argv)\n"
    }
    attrs {
      name: "op_namescope"
      type: STRING
      s: "/"
    }
    attrs {
      name: "op_role"
      type: INT
      i: 0
    }
  }
}
version {
  version: 0
}
