# Copyright (c) 2020 PaddlePaddle Authors. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

runner:
  train_data_dir: "data/train"
  train_reader_path: "senti_clas_reader" # importlib format
  use_gpu: False
  use_auc: False
  train_batch_size: 2
  epochs: 3
  print_interval: 2
  #model_init_path: "output_model/0" # init model
  model_save_path: "output_model_textcnn"
  test_data_dir: "data/train"
  infer_reader_path: "senti_clas_reader" # importlib format
  infer_batch_size: 5
  infer_load_path: "output_model_textcnn"
  infer_start_epoch: 0
  infer_end_epoch: 3

hyper_parameters:
  optimizer:
    class: Adagrad
    learning_rate: 0.001
  is_sparse: False
  dict_dim: 33257
  max_len: 100
  cnn_dim: 128
  cnn_filter_size1: 1
  cnn_filter_size2: 2
  cnn_filter_size3: 3
  emb_dim: 128
  hid_dim: 96
  class_dim: 2
