blocks {
  idx: 0
  parent_idx: -1
  vars {
    name: "fc_5.b_0"
    type {
      type: LOD_TENSOR
      lod_tensor {
        tensor {
          data_type: FP32
          dims: 1
        }
      }
    }
    persistable: true
  }
  vars {
    name: "fc_5.w_0"
    type {
      type: LOD_TENSOR
      lod_tensor {
        tensor {
          data_type: FP32
          dims: 127
          dims: 1
        }
      }
    }
    persistable: true
  }
  vars {
    name: "fc_0.w_0"
    type {
      type: LOD_TENSOR
      lod_tensor {
        tensor {
          data_type: FP32
          dims: 3672
          dims: 511
        }
      }
    }
    persistable: true
  }
  vars {
    name: "fc_0.b_0"
    type {
      type: LOD_TENSOR
      lod_tensor {
        tensor {
          data_type: FP32
          dims: 511
        }
      }
    }
    persistable: true
  }
  vars {
    name: "fc_1.b_0"
    type {
      type: LOD_TENSOR
      lod_tensor {
        tensor {
          data_type: FP32
          dims: 255
        }
      }
    }
    persistable: true
  }
  vars {
    name: "fc_2.w_0"
    type {
      type: LOD_TENSOR
      lod_tensor {
        tensor {
          data_type: FP32
          dims: 255
          dims: 127
        }
      }
    }
    persistable: true
  }
  vars {
    name: "fc_3.w_0"
    type {
      type: LOD_TENSOR
      lod_tensor {
        tensor {
          data_type: FP32
          dims: 127
          dims: 127
        }
      }
    }
    persistable: true
  }
  vars {
    name: "fc_2.b_0"
    type {
      type: LOD_TENSOR
      lod_tensor {
        tensor {
          data_type: FP32
          dims: 127
        }
      }
    }
    persistable: true
  }
  vars {
    name: "fc_4.b_0"
    type {
      type: LOD_TENSOR
      lod_tensor {
        tensor {
          data_type: FP32
          dims: 127
        }
      }
    }
    persistable: true
  }
  vars {
    name: "fc_1.w_0"
    type {
      type: LOD_TENSOR
      lod_tensor {
        tensor {
          data_type: FP32
          dims: 511
          dims: 255
        }
      }
    }
    persistable: true
  }
  vars {
    name: "fc_3.b_0"
    type {
      type: LOD_TENSOR
      lod_tensor {
        tensor {
          data_type: FP32
          dims: 127
        }
      }
    }
    persistable: true
  }
  vars {
    name: "fc_4.w_0"
    type {
      type: LOD_TENSOR
      lod_tensor {
        tensor {
          data_type: FP32
          dims: 127
          dims: 127
        }
      }
    }
    persistable: true
  }
  ops {
    outputs {
      parameter: "Out"
      arguments: "fc_5.b_0"
    }
    type: "gaussian_random"
    attrs {
      name: "op_role_var"
      type: STRINGS
    }
    attrs {
      name: "op_callstack"
      type: STRINGS
      strings: "  File \"/home/xiexionghang/paddle/py-paddle/python/lib/python2.7/site-packages/paddle/fluid/framework.py\", line 1851, in _prepend_op\n    attrs=kwargs.get(\"attrs\", None))\n"
      strings: "  File \"/home/xiexionghang/paddle/py-paddle/python/lib/python2.7/site-packages/paddle/fluid/initializer.py\", line 356, in __call__\n    stop_gradient=True)\n"
      strings: "  File \"/home/xiexionghang/paddle/py-paddle/python/lib/python2.7/site-packages/paddle/fluid/framework.py\", line 1736, in create_parameter\n    initializer(param, self)\n"
      strings: "  File \"/home/xiexionghang/paddle/py-paddle/python/lib/python2.7/site-packages/paddle/fluid/layer_helper_base.py\", line 328, in create_parameter\n    **attr._to_kwargs(with_initializer=True))\n"
      strings: "  File \"/home/xiexionghang/paddle/py-paddle/python/lib/python2.7/site-packages/paddle/fluid/layer_helper.py\", line 128, in append_bias_op\n    attr=bias_attr, shape=size, dtype=input_var.dtype, is_bias=True)\n"
      strings: "  File \"/home/xiexionghang/paddle/py-paddle/python/lib/python2.7/site-packages/paddle/fluid/layers/nn.py\", line 358, in fc\n    pre_activation = helper.append_bias_op(pre_bias, dim_start=num_flatten_dims)\n"
      strings: "  File \"update.py\", line 47, in inference\n    initializer=fluid.initializer.NormalInitializer(loc=0.0, scale=1.0 * scales[i])))\n"
      strings: "  File \"create_programs.py\", line 100, in build_and_save\n    inference_info = self._inference()\n"
      strings: "  File \"create_programs.py\", line 200, in main\n    builder.build_and_save()\n"
      strings: "  File \"create_programs.py\", line 203, in <module>\n    main(sys.argv)\n"
    }
    attrs {
      name: "op_namescope"
      type: STRING
      s: "/"
    }
    attrs {
      name: "op_role"
      type: INT
      i: 0
    }
    attrs {
      name: "use_mkldnn"
      type: BOOLEAN
      b: false
    }
    attrs {
      name: "dtype"
      type: INT
      i: 5
    }
    attrs {
      name: "seed"
      type: INT
      i: 0
    }
    attrs {
      name: "std"
      type: FLOAT
      f: 0.017747130245
    }
    attrs {
      name: "mean"
      type: FLOAT
      f: 0.0
    }
    attrs {
      name: "shape"
      type: LONGS
      longs: 1
    }
  }
  ops {
    outputs {
      parameter: "Out"
      arguments: "fc_5.w_0"
    }
    type: "gaussian_random"
    attrs {
      name: "op_role_var"
      type: STRINGS
    }
    attrs {
      name: "op_callstack"
      type: STRINGS
      strings: "  File \"/home/xiexionghang/paddle/py-paddle/python/lib/python2.7/site-packages/paddle/fluid/framework.py\", line 1851, in _prepend_op\n    attrs=kwargs.get(\"attrs\", None))\n"
      strings: "  File \"/home/xiexionghang/paddle/py-paddle/python/lib/python2.7/site-packages/paddle/fluid/initializer.py\", line 356, in __call__\n    stop_gradient=True)\n"
      strings: "  File \"/home/xiexionghang/paddle/py-paddle/python/lib/python2.7/site-packages/paddle/fluid/framework.py\", line 1736, in create_parameter\n    initializer(param, self)\n"
      strings: "  File \"/home/xiexionghang/paddle/py-paddle/python/lib/python2.7/site-packages/paddle/fluid/layer_helper_base.py\", line 328, in create_parameter\n    **attr._to_kwargs(with_initializer=True))\n"
      strings: "  File \"/home/xiexionghang/paddle/py-paddle/python/lib/python2.7/site-packages/paddle/fluid/layers/nn.py\", line 337, in fc\n    attr=param_attr, shape=param_shape, dtype=dtype, is_bias=False)\n"
      strings: "  File \"update.py\", line 47, in inference\n    initializer=fluid.initializer.NormalInitializer(loc=0.0, scale=1.0 * scales[i])))\n"
      strings: "  File \"create_programs.py\", line 100, in build_and_save\n    inference_info = self._inference()\n"
      strings: "  File \"create_programs.py\", line 200, in main\n    builder.build_and_save()\n"
      strings: "  File \"create_programs.py\", line 203, in <module>\n    main(sys.argv)\n"
    }
    attrs {
      name: "op_namescope"
      type: STRING
      s: "/"
    }
    attrs {
      name: "op_role"
      type: INT
      i: 0
    }
    attrs {
      name: "use_mkldnn"
      type: BOOLEAN
      b: false
    }
    attrs {
      name: "dtype"
      type: INT
      i: 5
    }
    attrs {
      name: "seed"
      type: INT
      i: 0
    }
    attrs {
      name: "std"
      type: FLOAT
      f: 0.017747130245
    }
    attrs {
      name: "mean"
      type: FLOAT
      f: 0.0
    }
    attrs {
      name: "shape"
      type: LONGS
      longs: 127
      longs: 1
    }
  }
  ops {
    outputs {
      parameter: "Out"
      arguments: "fc_4.b_0"
    }
    type: "gaussian_random"
    attrs {
      name: "op_role_var"
      type: STRINGS
    }
    attrs {
      name: "op_callstack"
      type: STRINGS
      strings: "  File \"/home/xiexionghang/paddle/py-paddle/python/lib/python2.7/site-packages/paddle/fluid/framework.py\", line 1851, in _prepend_op\n    attrs=kwargs.get(\"attrs\", None))\n"
      strings: "  File \"/home/xiexionghang/paddle/py-paddle/python/lib/python2.7/site-packages/paddle/fluid/initializer.py\", line 356, in __call__\n    stop_gradient=True)\n"
      strings: "  File \"/home/xiexionghang/paddle/py-paddle/python/lib/python2.7/site-packages/paddle/fluid/framework.py\", line 1736, in create_parameter\n    initializer(param, self)\n"
      strings: "  File \"/home/xiexionghang/paddle/py-paddle/python/lib/python2.7/site-packages/paddle/fluid/layer_helper_base.py\", line 328, in create_parameter\n    **attr._to_kwargs(with_initializer=True))\n"
      strings: "  File \"/home/xiexionghang/paddle/py-paddle/python/lib/python2.7/site-packages/paddle/fluid/layer_helper.py\", line 128, in append_bias_op\n    attr=bias_attr, shape=size, dtype=input_var.dtype, is_bias=True)\n"
      strings: "  File \"/home/xiexionghang/paddle/py-paddle/python/lib/python2.7/site-packages/paddle/fluid/layers/nn.py\", line 358, in fc\n    pre_activation = helper.append_bias_op(pre_bias, dim_start=num_flatten_dims)\n"
      strings: "  File \"update.py\", line 47, in inference\n    initializer=fluid.initializer.NormalInitializer(loc=0.0, scale=1.0 * scales[i])))\n"
      strings: "  File \"create_programs.py\", line 100, in build_and_save\n    inference_info = self._inference()\n"
      strings: "  File \"create_programs.py\", line 200, in main\n    builder.build_and_save()\n"
      strings: "  File \"create_programs.py\", line 203, in <module>\n    main(sys.argv)\n"
    }
    attrs {
      name: "op_namescope"
      type: STRING
      s: "/"
    }
    attrs {
      name: "op_role"
      type: INT
      i: 0
    }
    attrs {
      name: "use_mkldnn"
      type: BOOLEAN
      b: false
    }
    attrs {
      name: "dtype"
      type: INT
      i: 5
    }
    attrs {
      name: "seed"
      type: INT
      i: 0
    }
    attrs {
      name: "std"
      type: FLOAT
      f: 0.017747130245
    }
    attrs {
      name: "mean"
      type: FLOAT
      f: 0.0
    }
    attrs {
      name: "shape"
      type: LONGS
      longs: 127
    }
  }
  ops {
    outputs {
      parameter: "Out"
      arguments: "fc_4.w_0"
    }
    type: "gaussian_random"
    attrs {
      name: "op_role_var"
      type: STRINGS
    }
    attrs {
      name: "op_callstack"
      type: STRINGS
      strings: "  File \"/home/xiexionghang/paddle/py-paddle/python/lib/python2.7/site-packages/paddle/fluid/framework.py\", line 1851, in _prepend_op\n    attrs=kwargs.get(\"attrs\", None))\n"
      strings: "  File \"/home/xiexionghang/paddle/py-paddle/python/lib/python2.7/site-packages/paddle/fluid/initializer.py\", line 356, in __call__\n    stop_gradient=True)\n"
      strings: "  File \"/home/xiexionghang/paddle/py-paddle/python/lib/python2.7/site-packages/paddle/fluid/framework.py\", line 1736, in create_parameter\n    initializer(param, self)\n"
      strings: "  File \"/home/xiexionghang/paddle/py-paddle/python/lib/python2.7/site-packages/paddle/fluid/layer_helper_base.py\", line 328, in create_parameter\n    **attr._to_kwargs(with_initializer=True))\n"
      strings: "  File \"/home/xiexionghang/paddle/py-paddle/python/lib/python2.7/site-packages/paddle/fluid/layers/nn.py\", line 337, in fc\n    attr=param_attr, shape=param_shape, dtype=dtype, is_bias=False)\n"
      strings: "  File \"update.py\", line 47, in inference\n    initializer=fluid.initializer.NormalInitializer(loc=0.0, scale=1.0 * scales[i])))\n"
      strings: "  File \"create_programs.py\", line 100, in build_and_save\n    inference_info = self._inference()\n"
      strings: "  File \"create_programs.py\", line 200, in main\n    builder.build_and_save()\n"
      strings: "  File \"create_programs.py\", line 203, in <module>\n    main(sys.argv)\n"
    }
    attrs {
      name: "op_namescope"
      type: STRING
      s: "/"
    }
    attrs {
      name: "op_role"
      type: INT
      i: 0
    }
    attrs {
      name: "use_mkldnn"
      type: BOOLEAN
      b: false
    }
    attrs {
      name: "dtype"
      type: INT
      i: 5
    }
    attrs {
      name: "seed"
      type: INT
      i: 0
    }
    attrs {
      name: "std"
      type: FLOAT
      f: 0.017747130245
    }
    attrs {
      name: "mean"
      type: FLOAT
      f: 0.0
    }
    attrs {
      name: "shape"
      type: LONGS
      longs: 127
      longs: 127
    }
  }
  ops {
    outputs {
      parameter: "Out"
      arguments: "fc_3.b_0"
    }
    type: "gaussian_random"
    attrs {
      name: "op_role_var"
      type: STRINGS
    }
    attrs {
      name: "op_callstack"
      type: STRINGS
      strings: "  File \"/home/xiexionghang/paddle/py-paddle/python/lib/python2.7/site-packages/paddle/fluid/framework.py\", line 1851, in _prepend_op\n    attrs=kwargs.get(\"attrs\", None))\n"
      strings: "  File \"/home/xiexionghang/paddle/py-paddle/python/lib/python2.7/site-packages/paddle/fluid/initializer.py\", line 356, in __call__\n    stop_gradient=True)\n"
      strings: "  File \"/home/xiexionghang/paddle/py-paddle/python/lib/python2.7/site-packages/paddle/fluid/framework.py\", line 1736, in create_parameter\n    initializer(param, self)\n"
      strings: "  File \"/home/xiexionghang/paddle/py-paddle/python/lib/python2.7/site-packages/paddle/fluid/layer_helper_base.py\", line 328, in create_parameter\n    **attr._to_kwargs(with_initializer=True))\n"
      strings: "  File \"/home/xiexionghang/paddle/py-paddle/python/lib/python2.7/site-packages/paddle/fluid/layer_helper.py\", line 128, in append_bias_op\n    attr=bias_attr, shape=size, dtype=input_var.dtype, is_bias=True)\n"
      strings: "  File \"/home/xiexionghang/paddle/py-paddle/python/lib/python2.7/site-packages/paddle/fluid/layers/nn.py\", line 358, in fc\n    pre_activation = helper.append_bias_op(pre_bias, dim_start=num_flatten_dims)\n"
      strings: "  File \"update.py\", line 47, in inference\n    initializer=fluid.initializer.NormalInitializer(loc=0.0, scale=1.0 * scales[i])))\n"
      strings: "  File \"create_programs.py\", line 100, in build_and_save\n    inference_info = self._inference()\n"
      strings: "  File \"create_programs.py\", line 200, in main\n    builder.build_and_save()\n"
      strings: "  File \"create_programs.py\", line 203, in <module>\n    main(sys.argv)\n"
    }
    attrs {
      name: "op_namescope"
      type: STRING
      s: "/"
    }
    attrs {
      name: "op_role"
      type: INT
      i: 0
    }
    attrs {
      name: "use_mkldnn"
      type: BOOLEAN
      b: false
    }
    attrs {
      name: "dtype"
      type: INT
      i: 5
    }
    attrs {
      name: "seed"
      type: INT
      i: 0
    }
    attrs {
      name: "std"
      type: FLOAT
      f: 0.017747130245
    }
    attrs {
      name: "mean"
      type: FLOAT
      f: 0.0
    }
    attrs {
      name: "shape"
      type: LONGS
      longs: 127
    }
  }
  ops {
    outputs {
      parameter: "Out"
      arguments: "fc_3.w_0"
    }
    type: "gaussian_random"
    attrs {
      name: "op_role_var"
      type: STRINGS
    }
    attrs {
      name: "op_callstack"
      type: STRINGS
      strings: "  File \"/home/xiexionghang/paddle/py-paddle/python/lib/python2.7/site-packages/paddle/fluid/framework.py\", line 1851, in _prepend_op\n    attrs=kwargs.get(\"attrs\", None))\n"
      strings: "  File \"/home/xiexionghang/paddle/py-paddle/python/lib/python2.7/site-packages/paddle/fluid/initializer.py\", line 356, in __call__\n    stop_gradient=True)\n"
      strings: "  File \"/home/xiexionghang/paddle/py-paddle/python/lib/python2.7/site-packages/paddle/fluid/framework.py\", line 1736, in create_parameter\n    initializer(param, self)\n"
      strings: "  File \"/home/xiexionghang/paddle/py-paddle/python/lib/python2.7/site-packages/paddle/fluid/layer_helper_base.py\", line 328, in create_parameter\n    **attr._to_kwargs(with_initializer=True))\n"
      strings: "  File \"/home/xiexionghang/paddle/py-paddle/python/lib/python2.7/site-packages/paddle/fluid/layers/nn.py\", line 337, in fc\n    attr=param_attr, shape=param_shape, dtype=dtype, is_bias=False)\n"
      strings: "  File \"update.py\", line 47, in inference\n    initializer=fluid.initializer.NormalInitializer(loc=0.0, scale=1.0 * scales[i])))\n"
      strings: "  File \"create_programs.py\", line 100, in build_and_save\n    inference_info = self._inference()\n"
      strings: "  File \"create_programs.py\", line 200, in main\n    builder.build_and_save()\n"
      strings: "  File \"create_programs.py\", line 203, in <module>\n    main(sys.argv)\n"
    }
    attrs {
      name: "op_namescope"
      type: STRING
      s: "/"
    }
    attrs {
      name: "op_role"
      type: INT
      i: 0
    }
    attrs {
      name: "use_mkldnn"
      type: BOOLEAN
      b: false
    }
    attrs {
      name: "dtype"
      type: INT
      i: 5
    }
    attrs {
      name: "seed"
      type: INT
      i: 0
    }
    attrs {
      name: "std"
      type: FLOAT
      f: 0.017747130245
    }
    attrs {
      name: "mean"
      type: FLOAT
      f: 0.0
    }
    attrs {
      name: "shape"
      type: LONGS
      longs: 127
      longs: 127
    }
  }
  ops {
    outputs {
      parameter: "Out"
      arguments: "fc_2.b_0"
    }
    type: "gaussian_random"
    attrs {
      name: "op_role_var"
      type: STRINGS
    }
    attrs {
      name: "op_callstack"
      type: STRINGS
      strings: "  File \"/home/xiexionghang/paddle/py-paddle/python/lib/python2.7/site-packages/paddle/fluid/framework.py\", line 1851, in _prepend_op\n    attrs=kwargs.get(\"attrs\", None))\n"
      strings: "  File \"/home/xiexionghang/paddle/py-paddle/python/lib/python2.7/site-packages/paddle/fluid/initializer.py\", line 356, in __call__\n    stop_gradient=True)\n"
      strings: "  File \"/home/xiexionghang/paddle/py-paddle/python/lib/python2.7/site-packages/paddle/fluid/framework.py\", line 1736, in create_parameter\n    initializer(param, self)\n"
      strings: "  File \"/home/xiexionghang/paddle/py-paddle/python/lib/python2.7/site-packages/paddle/fluid/layer_helper_base.py\", line 328, in create_parameter\n    **attr._to_kwargs(with_initializer=True))\n"
      strings: "  File \"/home/xiexionghang/paddle/py-paddle/python/lib/python2.7/site-packages/paddle/fluid/layer_helper.py\", line 128, in append_bias_op\n    attr=bias_attr, shape=size, dtype=input_var.dtype, is_bias=True)\n"
      strings: "  File \"/home/xiexionghang/paddle/py-paddle/python/lib/python2.7/site-packages/paddle/fluid/layers/nn.py\", line 358, in fc\n    pre_activation = helper.append_bias_op(pre_bias, dim_start=num_flatten_dims)\n"
      strings: "  File \"update.py\", line 47, in inference\n    initializer=fluid.initializer.NormalInitializer(loc=0.0, scale=1.0 * scales[i])))\n"
      strings: "  File \"create_programs.py\", line 100, in build_and_save\n    inference_info = self._inference()\n"
      strings: "  File \"create_programs.py\", line 200, in main\n    builder.build_and_save()\n"
      strings: "  File \"create_programs.py\", line 203, in <module>\n    main(sys.argv)\n"
    }
    attrs {
      name: "op_namescope"
      type: STRING
      s: "/"
    }
    attrs {
      name: "op_role"
      type: INT
      i: 0
    }
    attrs {
      name: "use_mkldnn"
      type: BOOLEAN
      b: false
    }
    attrs {
      name: "dtype"
      type: INT
      i: 5
    }
    attrs {
      name: "seed"
      type: INT
      i: 0
    }
    attrs {
      name: "std"
      type: FLOAT
      f: 0.0125244855881
    }
    attrs {
      name: "mean"
      type: FLOAT
      f: 0.0
    }
    attrs {
      name: "shape"
      type: LONGS
      longs: 127
    }
  }
  ops {
    outputs {
      parameter: "Out"
      arguments: "fc_2.w_0"
    }
    type: "gaussian_random"
    attrs {
      name: "op_role_var"
      type: STRINGS
    }
    attrs {
      name: "op_callstack"
      type: STRINGS
      strings: "  File \"/home/xiexionghang/paddle/py-paddle/python/lib/python2.7/site-packages/paddle/fluid/framework.py\", line 1851, in _prepend_op\n    attrs=kwargs.get(\"attrs\", None))\n"
      strings: "  File \"/home/xiexionghang/paddle/py-paddle/python/lib/python2.7/site-packages/paddle/fluid/initializer.py\", line 356, in __call__\n    stop_gradient=True)\n"
      strings: "  File \"/home/xiexionghang/paddle/py-paddle/python/lib/python2.7/site-packages/paddle/fluid/framework.py\", line 1736, in create_parameter\n    initializer(param, self)\n"
      strings: "  File \"/home/xiexionghang/paddle/py-paddle/python/lib/python2.7/site-packages/paddle/fluid/layer_helper_base.py\", line 328, in create_parameter\n    **attr._to_kwargs(with_initializer=True))\n"
      strings: "  File \"/home/xiexionghang/paddle/py-paddle/python/lib/python2.7/site-packages/paddle/fluid/layers/nn.py\", line 337, in fc\n    attr=param_attr, shape=param_shape, dtype=dtype, is_bias=False)\n"
      strings: "  File \"update.py\", line 47, in inference\n    initializer=fluid.initializer.NormalInitializer(loc=0.0, scale=1.0 * scales[i])))\n"
      strings: "  File \"create_programs.py\", line 100, in build_and_save\n    inference_info = self._inference()\n"
      strings: "  File \"create_programs.py\", line 200, in main\n    builder.build_and_save()\n"
      strings: "  File \"create_programs.py\", line 203, in <module>\n    main(sys.argv)\n"
    }
    attrs {
      name: "op_namescope"
      type: STRING
      s: "/"
    }
    attrs {
      name: "op_role"
      type: INT
      i: 0
    }
    attrs {
      name: "use_mkldnn"
      type: BOOLEAN
      b: false
    }
    attrs {
      name: "dtype"
      type: INT
      i: 5
    }
    attrs {
      name: "seed"
      type: INT
      i: 0
    }
    attrs {
      name: "std"
      type: FLOAT
      f: 0.0125244855881
    }
    attrs {
      name: "mean"
      type: FLOAT
      f: 0.0
    }
    attrs {
      name: "shape"
      type: LONGS
      longs: 255
      longs: 127
    }
  }
  ops {
    outputs {
      parameter: "Out"
      arguments: "fc_1.b_0"
    }
    type: "gaussian_random"
    attrs {
      name: "op_role_var"
      type: STRINGS
    }
    attrs {
      name: "op_callstack"
      type: STRINGS
      strings: "  File \"/home/xiexionghang/paddle/py-paddle/python/lib/python2.7/site-packages/paddle/fluid/framework.py\", line 1851, in _prepend_op\n    attrs=kwargs.get(\"attrs\", None))\n"
      strings: "  File \"/home/xiexionghang/paddle/py-paddle/python/lib/python2.7/site-packages/paddle/fluid/initializer.py\", line 356, in __call__\n    stop_gradient=True)\n"
      strings: "  File \"/home/xiexionghang/paddle/py-paddle/python/lib/python2.7/site-packages/paddle/fluid/framework.py\", line 1736, in create_parameter\n    initializer(param, self)\n"
      strings: "  File \"/home/xiexionghang/paddle/py-paddle/python/lib/python2.7/site-packages/paddle/fluid/layer_helper_base.py\", line 328, in create_parameter\n    **attr._to_kwargs(with_initializer=True))\n"
      strings: "  File \"/home/xiexionghang/paddle/py-paddle/python/lib/python2.7/site-packages/paddle/fluid/layer_helper.py\", line 128, in append_bias_op\n    attr=bias_attr, shape=size, dtype=input_var.dtype, is_bias=True)\n"
      strings: "  File \"/home/xiexionghang/paddle/py-paddle/python/lib/python2.7/site-packages/paddle/fluid/layers/nn.py\", line 358, in fc\n    pre_activation = helper.append_bias_op(pre_bias, dim_start=num_flatten_dims)\n"
      strings: "  File \"update.py\", line 47, in inference\n    initializer=fluid.initializer.NormalInitializer(loc=0.0, scale=1.0 * scales[i])))\n"
      strings: "  File \"create_programs.py\", line 100, in build_and_save\n    inference_info = self._inference()\n"
      strings: "  File \"create_programs.py\", line 200, in main\n    builder.build_and_save()\n"
      strings: "  File \"create_programs.py\", line 203, in <module>\n    main(sys.argv)\n"
    }
    attrs {
      name: "op_namescope"
      type: STRING
      s: "/"
    }
    attrs {
      name: "op_role"
      type: INT
      i: 0
    }
    attrs {
      name: "use_mkldnn"
      type: BOOLEAN
      b: false
    }
    attrs {
      name: "dtype"
      type: INT
      i: 5
    }
    attrs {
      name: "seed"
      type: INT
      i: 0
    }
    attrs {
      name: "std"
      type: FLOAT
      f: 0.00884747877717
    }
    attrs {
      name: "mean"
      type: FLOAT
      f: 0.0
    }
    attrs {
      name: "shape"
      type: LONGS
      longs: 255
    }
  }
  ops {
    outputs {
      parameter: "Out"
      arguments: "fc_1.w_0"
    }
    type: "gaussian_random"
    attrs {
      name: "op_role_var"
      type: STRINGS
    }
    attrs {
      name: "op_callstack"
      type: STRINGS
      strings: "  File \"/home/xiexionghang/paddle/py-paddle/python/lib/python2.7/site-packages/paddle/fluid/framework.py\", line 1851, in _prepend_op\n    attrs=kwargs.get(\"attrs\", None))\n"
      strings: "  File \"/home/xiexionghang/paddle/py-paddle/python/lib/python2.7/site-packages/paddle/fluid/initializer.py\", line 356, in __call__\n    stop_gradient=True)\n"
      strings: "  File \"/home/xiexionghang/paddle/py-paddle/python/lib/python2.7/site-packages/paddle/fluid/framework.py\", line 1736, in create_parameter\n    initializer(param, self)\n"
      strings: "  File \"/home/xiexionghang/paddle/py-paddle/python/lib/python2.7/site-packages/paddle/fluid/layer_helper_base.py\", line 328, in create_parameter\n    **attr._to_kwargs(with_initializer=True))\n"
      strings: "  File \"/home/xiexionghang/paddle/py-paddle/python/lib/python2.7/site-packages/paddle/fluid/layers/nn.py\", line 337, in fc\n    attr=param_attr, shape=param_shape, dtype=dtype, is_bias=False)\n"
      strings: "  File \"update.py\", line 47, in inference\n    initializer=fluid.initializer.NormalInitializer(loc=0.0, scale=1.0 * scales[i])))\n"
      strings: "  File \"create_programs.py\", line 100, in build_and_save\n    inference_info = self._inference()\n"
      strings: "  File \"create_programs.py\", line 200, in main\n    builder.build_and_save()\n"
      strings: "  File \"create_programs.py\", line 203, in <module>\n    main(sys.argv)\n"
    }
    attrs {
      name: "op_namescope"
      type: STRING
      s: "/"
    }
    attrs {
      name: "op_role"
      type: INT
      i: 0
    }
    attrs {
      name: "use_mkldnn"
      type: BOOLEAN
      b: false
    }
    attrs {
      name: "dtype"
      type: INT
      i: 5
    }
    attrs {
      name: "seed"
      type: INT
      i: 0
    }
    attrs {
      name: "std"
      type: FLOAT
      f: 0.00884747877717
    }
    attrs {
      name: "mean"
      type: FLOAT
      f: 0.0
    }
    attrs {
      name: "shape"
      type: LONGS
      longs: 511
      longs: 255
    }
  }
  ops {
    outputs {
      parameter: "Out"
      arguments: "fc_0.b_0"
    }
    type: "gaussian_random"
    attrs {
      name: "op_role_var"
      type: STRINGS
    }
    attrs {
      name: "op_callstack"
      type: STRINGS
      strings: "  File \"/home/xiexionghang/paddle/py-paddle/python/lib/python2.7/site-packages/paddle/fluid/framework.py\", line 1851, in _prepend_op\n    attrs=kwargs.get(\"attrs\", None))\n"
      strings: "  File \"/home/xiexionghang/paddle/py-paddle/python/lib/python2.7/site-packages/paddle/fluid/initializer.py\", line 356, in __call__\n    stop_gradient=True)\n"
      strings: "  File \"/home/xiexionghang/paddle/py-paddle/python/lib/python2.7/site-packages/paddle/fluid/framework.py\", line 1736, in create_parameter\n    initializer(param, self)\n"
      strings: "  File \"/home/xiexionghang/paddle/py-paddle/python/lib/python2.7/site-packages/paddle/fluid/layer_helper_base.py\", line 328, in create_parameter\n    **attr._to_kwargs(with_initializer=True))\n"
      strings: "  File \"/home/xiexionghang/paddle/py-paddle/python/lib/python2.7/site-packages/paddle/fluid/layer_helper.py\", line 128, in append_bias_op\n    attr=bias_attr, shape=size, dtype=input_var.dtype, is_bias=True)\n"
      strings: "  File \"/home/xiexionghang/paddle/py-paddle/python/lib/python2.7/site-packages/paddle/fluid/layers/nn.py\", line 358, in fc\n    pre_activation = helper.append_bias_op(pre_bias, dim_start=num_flatten_dims)\n"
      strings: "  File \"update.py\", line 47, in inference\n    initializer=fluid.initializer.NormalInitializer(loc=0.0, scale=1.0 * scales[i])))\n"
      strings: "  File \"create_programs.py\", line 100, in build_and_save\n    inference_info = self._inference()\n"
      strings: "  File \"create_programs.py\", line 200, in main\n    builder.build_and_save()\n"
      strings: "  File \"create_programs.py\", line 203, in <module>\n    main(sys.argv)\n"
    }
    attrs {
      name: "op_namescope"
      type: STRING
      s: "/"
    }
    attrs {
      name: "op_role"
      type: INT
      i: 0
    }
    attrs {
      name: "use_mkldnn"
      type: BOOLEAN
      b: false
    }
    attrs {
      name: "dtype"
      type: INT
      i: 5
    }
    attrs {
      name: "seed"
      type: INT
      i: 0
    }
    attrs {
      name: "std"
      type: FLOAT
      f: 0.00330049172044
    }
    attrs {
      name: "mean"
      type: FLOAT
      f: 0.0
    }
    attrs {
      name: "shape"
      type: LONGS
      longs: 511
    }
  }
  ops {
    outputs {
      parameter: "Out"
      arguments: "fc_0.w_0"
    }
    type: "gaussian_random"
    attrs {
      name: "op_role_var"
      type: STRINGS
    }
    attrs {
      name: "op_callstack"
      type: STRINGS
      strings: "  File \"/home/xiexionghang/paddle/py-paddle/python/lib/python2.7/site-packages/paddle/fluid/framework.py\", line 1851, in _prepend_op\n    attrs=kwargs.get(\"attrs\", None))\n"
      strings: "  File \"/home/xiexionghang/paddle/py-paddle/python/lib/python2.7/site-packages/paddle/fluid/initializer.py\", line 356, in __call__\n    stop_gradient=True)\n"
      strings: "  File \"/home/xiexionghang/paddle/py-paddle/python/lib/python2.7/site-packages/paddle/fluid/framework.py\", line 1736, in create_parameter\n    initializer(param, self)\n"
      strings: "  File \"/home/xiexionghang/paddle/py-paddle/python/lib/python2.7/site-packages/paddle/fluid/layer_helper_base.py\", line 328, in create_parameter\n    **attr._to_kwargs(with_initializer=True))\n"
      strings: "  File \"/home/xiexionghang/paddle/py-paddle/python/lib/python2.7/site-packages/paddle/fluid/layers/nn.py\", line 337, in fc\n    attr=param_attr, shape=param_shape, dtype=dtype, is_bias=False)\n"
      strings: "  File \"update.py\", line 47, in inference\n    initializer=fluid.initializer.NormalInitializer(loc=0.0, scale=1.0 * scales[i])))\n"
      strings: "  File \"create_programs.py\", line 100, in build_and_save\n    inference_info = self._inference()\n"
      strings: "  File \"create_programs.py\", line 200, in main\n    builder.build_and_save()\n"
      strings: "  File \"create_programs.py\", line 203, in <module>\n    main(sys.argv)\n"
    }
    attrs {
      name: "op_namescope"
      type: STRING
      s: "/"
    }
    attrs {
      name: "op_role"
      type: INT
      i: 0
    }
    attrs {
      name: "use_mkldnn"
      type: BOOLEAN
      b: false
    }
    attrs {
      name: "dtype"
      type: INT
      i: 5
    }
    attrs {
      name: "seed"
      type: INT
      i: 0
    }
    attrs {
      name: "std"
      type: FLOAT
      f: 0.00330049172044
    }
    attrs {
      name: "mean"
      type: FLOAT
      f: 0.0
    }
    attrs {
      name: "shape"
      type: LONGS
      longs: 3672
      longs: 511
    }
  }
}
version {
  version: 0
}
