# Copyright (c) 2020 PaddlePaddle Authors. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# global settings

runner:
  train_data_dir: "../../../datasets/Beauty/data/train"
  train_reader_path: "data_reader" # importlib format
  use_gpu: True
  train_batch_size: 1
  data_batch_size: 256
  epochs: 50
  print_interval: 100

  model_save_path: "output_model_bert4rec_all"
  test_data_dir: "../../../datasets/Beauty/data/test"
  infer_reader_path: "data_reader" # importlib format
  infer_batch_size: 1
  infer_load_path: "output_model_bert4rec_all"
  infer_start_epoch: 49
  infer_end_epoch: 50


# hyper parameters of user-defined network
hyper_parameters:
  # optimizer config
  optimizer:
    learning_rate: 0.0001
    weight_decay: 0.01

  _emb_size: 64
  _n_layer: 2
  _n_head: 2
  _voc_size: 54546
  _max_position_seq_len: 50
  _sent_types: 2
  hidden_act: "gelu"
  _dropout: 0.5
  _attention_dropout: 0.2
  _param_initializer: 0.02
  num_test_user: 40226

