#!/bin/bash

export PATH=/bin/:$PATH
set -x

source conf/env.conf

echo "# This file is automatically generated. Don't change it." > conf/qsub_f.conf
echo "SERVER=$MPI_SERVER" >> conf/qsub_f.conf
echo "QUEUE=$MPI_QUEUE" >> conf/qsub_f.conf
echo "PRIORITY=$MPI_PRIORITY" >> conf/qsub_f.conf

export HADOOP_HOME=$HADOOP_HOME

sh scripts/compake_runable_package.sh 

$HPC_HOME/bin/qsub_f \
    -N $MPI_JOB_NAME \
    --conf conf/qsub_f.conf \
    --hdfs $HADOOP_FS \
    --ugi $HADOOP_UGI \
    --hout $HDFS_ROOT \
    --files package \
    -l nodes=$MPI_NODE_NUM,walltime=$MPI_WALL_TIME,pmem-hard=$MPI_NODE_MEM,pcpu-soft=180,pnetin-soft=1000,pnetout-soft=1000 \
    scripts/start_feed_trainer.sh

if [ $? -ne 0 ]; then
    echo -e "qsub_f failed, please check the config or get help from abacus RD\n"
    exit -1
fi

exit 0
