# workspace
#workspace: "models/rank/dnn"


runner:
  train_data_dir: "data/train"
  train_reader_path: "dig_reader" # importlib format
  use_gpu: True
  use_fleet: False
  use_auc: True
  train_batch_size: 10
  epochs: 5
  print_interval: 1
  model_save_path: "output_model_gnn"
  infer_batch_size: 50
  infer_reader_path: "dig_reader" # importlib format
  test_data_dir: "data/test"
  infer_load_path: "output_model_gnn"
  infer_start_epoch: 0
  infer_end_epoch: 5 #与训练的epoch对应，每一个epoch保存和加载模型验证


# hyper parameters of user-defined network
hyper_parameters:
  # optimizer config
  optimizer:
    class: Adam
    learning_rate: 0.001
    decay_rate: 0.1
    l2: 0.00001
  # user-defined <key, value> pairs
  sparse_feature_number: 43098
  sparse_feature_dim: 100
  gnn_propogation_steps: 1
