# Copyright (c) 2020 PaddlePaddle Authors. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

runner:
  train_data_dir: "../../../datasets/Multi_MNIST_DselectK/train"
  train_reader_path: "multiMNIST_reader" # importlib format
  use_gpu: True
  use_auc: True
  train_batch_size: 256
  epochs: 100
  print_interval: 32
  #model_init_path: "output_model/0" # init model
  model_save_path: "output_model_dselect_k_all"
  test_data_dir: "../../../datasets/Multi_MNIST_DselectK/test"
  infer_batch_size: 256
  infer_reader_path: "multiMNIST_reader" # importlib format
  infer_load_path: "output_model_dselect_k_all"
  infer_start_epoch: 0
  infer_end_epoch: 100
  #use inference save model
  use_inference: False
  save_inference_feed_varnames: ["input"]
  save_inference_fetch_varnames: ["slice_0.tmp_0", "slice_1.tmp_0"]

hyper_parameters:
  feature_size: 1296
  top_k: 2
  expert_num: 8
  gate_num: 2
  expert_size: 50
  tower_size: 8
  optimizer:
    class: adam
    learning_rate: 0.001
    strategy: async
