# Copyright (c) 2022 PaddlePaddle Authors. All Rights Reserved.
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

runner:
  train_data_dir: "../../../datasets/KDD2012_track2/train"
  train_reader_path: "dpin_reader" # importlib format
  use_gpu: True
  use_auc: True
  train_batch_size: 1024
  epochs: 20
  print_interval: 1000
  #model_init_path: "output_model_all_dpin/0" # init model
  model_save_path: "output_model_all_dpin"
  infer_batch_size: 1024
  infer_reader_path: "dpin_reader" # importlib format
  test_data_dir:  "../../../datasets/KDD2012_track2/test"
  infer_load_path: "output_model_all_dpin"
  infer_start_epoch: 0
  infer_end_epoch: 20

# hyper parameters of user-defined network
hyper_parameters:
  is_sparse: True
  embedding_dim: 8 # Embedding dimension
  K: 3 # the number of position
  L: 10
  max_item: 455565
  max_context: 14616
  d_model: 64
  h: 2
  optimizer:
    class: sgd
    learning_rate: 0.05
    strategy: async
