# Copyright (c) 2020 PaddlePaddle Authors. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
workspace: "./"

hyper_parameters:
  optimizer:
    learning_rate: 1.0
    decay_steps: 100000
    decay_rate: 0.999
    class: sgd
    strategy: async
  sparse_feature_number: 354051
  sparse_feature_dim: 300
  with_shuffle_batch: False
  neg_num: 5
  window_size: 5

mode: [single_cpu_train, single_cpu_infer]
runner:
- name: single_cpu_train
  class: train
  epochs: 5
  device: cpu
  print_interval: 1000
  phases: [phase1]
- name: single_cpu_infer
  class: infer
  device: cpu
  init_model_path: "increment_w2v" 
  print_interval: 1
  phases: [phase2]


dataset:
- name: dataset_train 
  batch_size: 100
  type: DataLoader 
  data_path: "{workspace}/data/train"
  word_count_dict_path: "{workspace}/data/dict/word_count_dict.txt"
  data_converter: "{workspace}/w2v_reader.py"
- name: dataset_infer 
  batch_size: 2000
  type: DataLoader 
  data_path: "{workspace}/data/test"
  word_id_dict_path: "{workspace}/data/dict/word_id_dict.txt"
  data_converter: "{workspace}/w2v_evaluate_reader.py"

phase:
- name: phase1
  model: "{workspace}/model.py" 
  dataset_name: dataset_train 
  thread_num: 5
- name: phase2
  model: "{workspace}/model.py" 
  dataset_name: dataset_infer 
  thread_num: 1
